package com.aether.launcher.system

import android.os.Bundle
import android.graphics.Color
import android.view.Gravity
import android.widget.*
import androidx.activity.ComponentActivity

class NotificationSettingsActivity:ComponentActivity(){
 private val store by lazy{NotificationPresentationStore(this)}
 private var s=store.load()
 override fun onCreate(b:Bundle?){super.onCreate(b);draw()}
 private fun draw(){val root=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(20,28,20,40);setBackgroundColor(0xFFF7F7FB.toInt())};root.addView(TextView(this).apply{text="Notification";textSize=30f;setTextColor(Color.BLACK);typeface=android.graphics.Typeface.DEFAULT_BOLD});section(root,"DND & GAME MODE");toggle(root,"Show notifications during DND",s.showDuringDnd){s=s.copy(showDuringDnd=it);save()};toggle(root,"Notifications during games",s.showDuringGames){s=s.copy(showDuringGames=it);save()};section(root,"SILENT NOTIFICATIONS");toggle(root,"Expand silent app notifications",s.expandSilent){s=s.copy(expandSilent=it);save()};section(root,"NOTIFICATION APPEARANCE");toggle(root,"Show profile / number badge",s.showProfileBadge){s=s.copy(showProfileBadge=it);save()};toggle(root,"Show number badge",s.showNumberBadge){s=s.copy(showNumberBadge=it);save()};toggle(root,"Show arrow icon",s.showArrow){s=s.copy(showArrow=it);save()};toggle(root,"Hide when no cover image",s.hideWithoutCover){s=s.copy(hideWithoutCover=it);save()};section(root,"SMALL POPUP VISIBILITY");choice(root){s=s.copy(smallPopupMode=it);save()};section(root,"EXPANDED POPUP VISIBILITY");seek(root,s.expandedSeconds){s=s.copy(expandedSeconds=it);save()};toggle(root,"Swipe to remove notification",s.swipeToRemove){s=s.copy(swipeToRemove=it);save()};setContentView(ScrollView(this).apply{addView(root)})}
 private fun section(r:LinearLayout,t:String){r.addView(TextView(this).apply{text=t;textSize=13f;setTextColor(0xFF77777F.toInt());setPadding(2,18,0,8)})}
 private fun toggle(r:LinearLayout,t:String,v:Boolean,a:(Boolean)->Unit){val x=LinearLayout(this).apply{gravity=Gravity.CENTER_VERTICAL;setPadding(16,0,8,0);setBackgroundColor(Color.WHITE)};x.addView(TextView(this).apply{text=t;textSize=16f;setTextColor(Color.BLACK)},LinearLayout.LayoutParams(0,64,1f));x.addView(Switch(this).apply{isChecked=v;setOnCheckedChangeListener{_,z->a(z)}});r.addView(x,LinearLayout.LayoutParams(-1,70).apply{bottomMargin=7})}
 private fun choice(r:LinearLayout,a:(SmallPopupMode)->Unit){val x=LinearLayout(this).apply{gravity=Gravity.CENTER_VERTICAL;setPadding(16,0,8,0);setBackgroundColor(Color.WHITE)};x.addView(TextView(this).apply{text="Popup lifetime";textSize=16f;setTextColor(Color.BLACK)},LinearLayout.LayoutParams(0,64,1f));val sp=Spinner(this);sp.adapter=ArrayAdapter(this,android.R.layout.simple_spinner_dropdown_item,SmallPopupMode.values().map{it.name.replace('_',' ').lowercase().replaceFirstChar{c->c.uppercase()}});sp.setSelection(SmallPopupMode.values().indexOf(s.smallPopupMode));sp.setOnItemSelectedListener(object:AdapterView.OnItemSelectedListener{override fun onItemSelected(p:AdapterView<*>?,v:android.view.View?,pos:Int,id:Long)=a(SmallPopupMode.values()[pos]);override fun onNothingSelected(p:AdapterView<*>?){}});x.addView(sp,LinearLayout.LayoutParams(190,64));r.addView(x,LinearLayout.LayoutParams(-1,70).apply{bottomMargin=7})}
 private fun seek(r:LinearLayout,v:Int,a:(Int)->Unit){val x=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(16,8,16,8);setBackgroundColor(Color.WHITE)};val out=TextView(this).apply{text="$v seconds";textSize=16f;setTextColor(0xFF168BFF.toInt())};x.addView(out);x.addView(SeekBar(this).apply{max=29;progress=v-1;setOnSeekBarChangeListener(object:SeekBar.OnSeekBarChangeListener{override fun onProgressChanged(b:SeekBar?,p:Int,f:Boolean){out.text="${p+1} seconds";if(f)a(p+1)};override fun onStartTrackingTouch(b:SeekBar?){ };override fun onStopTrackingTouch(b:SeekBar?){ }})});r.addView(x,LinearLayout.LayoutParams(-1,90))}
 private fun save(){store.save(s)}
}
