package com.aether.launcher.ui

import android.app.*
import android.content.*
import android.graphics.*
import android.graphics.drawable.Drawable
import android.os.Bundle
import android.provider.Settings
import android.view.*
import android.widget.EditText
import androidx.dynamicanimation.animation.*
import com.aether.launcher.*
import com.aether.launcher.engine.launcher.AppInfo
import com.aether.launcher.settings.*
import com.aether.launcher.system.AetherSystemActions
import java.util.UUID
import kotlin.math.abs

object AetherSurface { const val DRAWER="drawer";const val HISTORY="history";const val QUICK="quick";const val CONTROL="control";const val NOTIFICATIONS="notifications";const val WIDGETS="widgets";const val FOLDER="folder";const val MULTITASK="multitask";const val SETUP_CENTER="setup_center";const val ABOUT="about" }

class AetherSurfaceActivity:Activity(){
 override fun onCreate(b:Bundle?){super.onCreate(b);AetherRuntime.initialize(applicationContext);val root=AetherGlassRoot(this);root.attach(AetherSurfaceView(this,intent.getStringExtra("surface")?:AetherSurface.DRAWER,intent.getStringExtra("title"),intent.getStringExtra("folder_id")));setContentView(root)}
}

class AetherSurfaceView(c:Context,private val surface:String,private val folderTitle:String?,private val folderId:String?):View(c){
 private val p=Paint(3);private val d get()=resources.displayMetrics.density;private var downX=0f;private var downY=0f
 private val launcher get()=AetherRuntime.registry.launcher;private val apps get()=launcher.apps();private val history=AetherHistoryStore(c);private val dock=AetherDockStore(c);private val folders=AetherFolderStore(c);private val cfg=AetherSettingsStore(c)
 init{translationY=18f*d;SpringAnimation(this,DynamicAnimation.TRANSLATION_Y).apply{spring=SpringForce(0f).apply{stiffness=520f;dampingRatio=.82f}}.start()}
 override fun onDraw(c:Canvas){val w=width.toFloat();val h=height.toFloat();c.drawColor(0xFF080A0E.toInt());p.color=Color.WHITE;p.textSize=28f*d;p.typeface=Typeface.DEFAULT_BOLD;c.drawText(title(),24f*d,50f*d,p);p.typeface=Typeface.DEFAULT;p.color=0xB8FFFFFF.toInt();p.textSize=12f*d;c.drawText(subtitle(),24f*d,74f*d,p);when(surface){AetherSurface.DRAWER->drawer(c,w,h);AetherSurface.HISTORY->historySurface(c,w,h);AetherSurface.QUICK->quick(c,w,h);AetherSurface.CONTROL->control(c,w,h);AetherSurface.NOTIFICATIONS->notifications(c,w,h);AetherSurface.WIDGETS->widgets(c,w,h);AetherSurface.FOLDER->folder(c,w,h);AetherSurface.MULTITASK->multi(c,w,h);AetherSurface.SETUP_CENTER->setup(c,w,h);else->about(c,w,h)}}
 private fun title()=when(surface){AetherSurface.DRAWER->"App Drawer";AetherSurface.HISTORY->"History";AetherSurface.QUICK->"Quick Space";AetherSurface.CONTROL->"Control Center";AetherSurface.NOTIFICATIONS->"Notifications";AetherSurface.WIDGETS->"Live Widgets";AetherSurface.FOLDER->folderTitle?:"Folder";AetherSurface.MULTITASK->"Aether Multitask";AetherSurface.SETUP_CENTER->"Setup Center";else->"About Aether"}
 private fun subtitle()=when(surface){AetherSurface.DRAWER->"Search, organize and launch real installed apps";AetherSurface.HISTORY->"Recently launched • persistent on-device history";AetherSurface.QUICK->"Real tools • OS-backed actions";AetherSurface.CONTROL->"System-backed controls";AetherSurface.NOTIFICATIONS->"Notification Access data";AetherSurface.WIDGETS->"Android AppWidget providers";AetherSurface.MULTITASK->"Android windowing where supported";else->""}
 private fun glass(c:Canvas,r:RectF,rad:Float){p.color=0xB7161B22.toInt();p.setShadowLayer(16f*d,0f,8f*d,0x70000000.toInt());c.drawRoundRect(r,rad,rad,p);p.clearShadowLayer();p.color=0x38FFFFFF;c.drawRoundRect(RectF(r.left+1,r.top+1,r.right-1,r.bottom-1),rad,rad,p)}
 private fun button(c:Canvas,l:Float,t:Float,r:Float,b:Float,s:String){glass(c,RectF(l,t,r,b),18f*d);p.color=Color.WHITE;p.textAlign=Paint.Align.CENTER;p.textSize=13f*d;c.drawText(s,(l+r)/2,t+33f*d,p)}
 private fun drawer(c:Canvas,w:Float,h:Float){button(c,22f*d,92f*d,w*.46f,146f*d,"⌕  Search apps");button(c,w*.54f,92f*d,w-22f*d,146f*d,"＋  New folder");val g=cfg.load().grid;grid(c,w,h,apps,g.columns.coerceIn(3,7),164f*d)}
 private fun historySurface(c:Canvas,w:Float,h:Float){button(c,w*.57f,92f*d,w-22f*d,146f*d,"Clear history");val list=history.load().mapNotNull{e->apps.firstOrNull{it.packageName==e.packageName}}.distinctBy{it.packageName};if(list.isEmpty())empty(c,w,h,"No launch history yet.")else grid(c,w,h,list,3,164f*d)}
 private fun folder(c:Canvas,w:Float,h:Float){val f=folders.load().firstOrNull{it.id==folderId||it.name==folderTitle};val list=f?.packages?.mapNotNull{pkg->apps.firstOrNull{it.packageName==pkg}}.orEmpty();if(list.isEmpty())empty(c,w,h,"This folder is empty.")else grid(c,w,h,list,3,106f*d)}
 private fun grid(c:Canvas,w:Float,h:Float,list:List<AppInfo>,cols:Int,top:Float){val gap=12f*d;val left=22f*d;val cell=(w-left*2-gap*(cols-1))/cols;val size=46f*d;list.take(48).forEachIndexed{i,a->{val col=i%cols;val row=i/cols;val x=left+col*(cell+gap);val y=top+row*84f*d;glass(c,RectF(x,y,x+cell,y+66f*d),20f*d);icon(c,a.packageName,RectF(x+cell/2-size/2,y+7*d,x+cell/2+size/2,y+7*d+size));p.color=Color.WHITE;p.textAlign=Paint.Align.CENTER;p.textSize=10f*d;c.drawText(a.label.take(14),x+cell/2,y+82f*d,p)}}}
 private fun icon(c:Canvas,pkg:String,r:RectF){launcher.icon(pkg)?.let{d:Drawable->d.setBounds(r.left.toInt(),r.top.toInt(),r.right.toInt(),r.bottom.toInt());d.draw(c)}}
 private fun empty(c:Canvas,w:Float,h:Float,s:String){p.color=0xBFFFFFFF.toInt();p.textAlign=Paint.Align.CENTER;p.textSize=14f*d;c.drawText(s,w/2,h*.44f,p)}
 private fun quick(c:Canvas,w:Float,h:Float){listOf("Home","Notes","Voice","Calculator","Screenshot","Clipboard","Widgets","Settings").forEachIndexed{i,s->{val y=106f*d+i*66f*d;glass(c,RectF(24f*d,y,w-24f*d,y+54f*d),18f*d);p.color=Color.WHITE;p.textAlign=Paint.Align.LEFT;p.textSize=14f*d;c.drawText(s,42f*d,y+33f*d,p)}}}
 private fun control(c:Canvas,w:Float,h:Float){listOf("Wi-Fi","Bluetooth","Airplane","Rotation","Flashlight","Brightness +","Brightness −","DND","System settings").forEachIndexed{i,s->{val col=i%2;val row=i/2;val x=24f*d+col*w*.47f;val y=104f*d+row*70f*d;glass(c,RectF(x,y,x+w*.43f,y+58f*d),18f*d);p.color=Color.WHITE;p.textAlign=Paint.Align.LEFT;p.textSize=13f*d;c.drawText(s,x+16f*d,y+32f*d,p)}}}
 private fun notifications(c:Canvas,w:Float,h:Float){val ns=AetherRuntime.registry.notifications.all();if(ns.isEmpty()){empty(c,w,h,"Enable Notification Access to populate this surface.");return};ns.take(10).forEachIndexed{i,n->{val y=104f*d+i*78f*d;glass(c,RectF(22f*d,y,w-22f*d,y+66f*d),20f*d);p.color=Color.WHITE;p.textAlign=Paint.Align.LEFT;p.textSize=13f*d;c.drawText(n.title.ifBlank{"Notification"},38f*d,y+25f*d,p);p.color=0xBFFFFFFF.toInt();p.textSize=11f*d;c.drawText(n.text.take(72),38f*d,y+45f*d,p)}}}
 private fun widgets(c:Canvas,w:Float,h:Float){glass(c,RectF(24f*d,106f*d,w-24f*d,198f*d),26f*d);p.color=Color.WHITE;p.textAlign=Paint.Align.LEFT;p.textSize=18f*d;c.drawText("Live Android widgets",44f*d,146f*d,p);p.color=0xBFFFFFFF.toInt();p.textSize=12f*d;c.drawText("Real provider-backed widgets with persistence.",44f*d,169f*d,p);button(c,24f*d,216f*d,w-24f*d,280f*d,"＋  Add widget")}
 private fun multi(c:Canvas,w:Float,h:Float){val list=history.load().mapNotNull{e->apps.firstOrNull{it.packageName==e.packageName}}.distinctBy{it.packageName}.take(4);if(list.isEmpty()){empty(c,w,h,"No recent apps yet.");return};list.forEachIndexed{i,a->{val y=108f*d+i*84f*d;glass(c,RectF(24f*d,y,w-24f*d,y+70f*d),20f*d);icon(c,a.packageName,RectF(40f*d,y+11f*d,86f*d,y+57f*d));p.color=Color.WHITE;p.textAlign=Paint.Align.LEFT;p.textSize=13f*d;c.drawText(a.label,100f*d,y+29f*d,p)}}}
 private fun setup(c:Canvas,w:Float,h:Float){listOf("Default launcher","Overlay permission","Notification access","Accessibility","Write system settings","Aether Settings").forEachIndexed{i,s->{val y=110f*d+i*68f*d;glass(c,RectF(22f*d,y,w-22f*d,y+56f*d),18f*d);p.color=Color.WHITE;p.textAlign=Paint.Align.LEFT;p.textSize=13f*d;c.drawText(s,40f*d,y+31f*d,p)}}}
 private fun about(c:Canvas,w:Float,h:Float){glass(c,RectF(26f*d,130f*d,w-26f*d,h-120f*d),32f*d);p.color=Color.WHITE;p.textAlign=Paint.Align.CENTER;p.textSize=56f*d;c.drawText("A",w/2,230f*d,p);p.textSize=20f*d;c.drawText("AETHER",w/2,270f*d,p);p.color=0xBFFFFFFF.toInt();p.textSize=12f*d;c.drawText("Android launcher + interaction layer",w/2,300f*d,p)}
 override fun onTouchEvent(e:MotionEvent):Boolean{when(e.actionMasked){MotionEvent.ACTION_DOWN->{downX=e.x;downY=e.y;return true};MotionEvent.ACTION_UP->{val dx=e.x-downX;val dy=e.y-downY;if(abs(dx)>80*d||abs(dy)>80*d){animate().translationY(height*.06f).alpha(.35f).setDuration(150).withEndAction{(context as?Activity)?.finish()}.start();return true};when(surface){AetherSurface.DRAWER->drawerTap(e.x,e.y);AetherSurface.HISTORY->historyTap(e.x,e.y);AetherSurface.WIDGETS->if(downY>210*d)context.startActivity(Intent(context,AetherWidgetHostActivity::class.java));AetherSurface.FOLDER->launchAt(e.x,e.y,3,106*d,folderApps());AetherSurface.MULTITASK->multiTap(e.y);AetherSurface.QUICK->quickTap(e.y);AetherSurface.CONTROL->controlTap(e.x,e.y);AetherSurface.SETUP_CENTER->setupTap(e.y)};return true}};return true}
 private fun drawerTap(x:Float,y:Float){if(y in 90*d..154*d){if(x<width*.5f)context.startActivity(Intent(context,AetherSearchActivity::class.java))else createFolder();return};if(y>154*d)launchAt(x,y,cfg.load().grid.columns.coerceIn(3,7),164*d,apps)}
 private fun historyTap(x:Float,y:Float){if(y in 90*d..154*d&&x>width*.5f){history.clear();invalidate();return};launchAt(x,y,3,164*d,history.load().mapNotNull{h->apps.firstOrNull{it.packageName==h.packageName}}.distinctBy{it.packageName})}
 private fun launchAt(x:Float,y:Float,cols:Int,top:Float,list:List<AppInfo>){val gap=12*d;val left=22*d;val cell=(width-left*2-gap*(cols-1))/cols;val row=((y-top)/(84*d)).toInt();val col=((x-left)/(cell+gap)).toInt();val i=row*cols+col;if(col in 0 until cols&&row>=0&&i in list.indices){history.record(list[i].packageName);launcher.launchIntent(list[i].packageName)?.let{context.startActivity(it)}}}
 private fun folderApps()=folders.load().firstOrNull{it.id==folderId||it.name==folderTitle}?.packages?.mapNotNull{pkg->apps.firstOrNull{it.packageName==pkg}}.orEmpty()
 private fun createFolder(){val selected=BooleanArray(apps.size);AlertDialog.Builder(context).setTitle("New Aether Folder").setMultiChoiceItems(apps.map{it.label}.toTypedArray(),selected){_,i,v->selected[i]=v}.setNegativeButton("Cancel",null).setPositiveButton("Next"){_,_->val chosen=apps.indices.filter{selected[it]}.map{apps[it].packageName};if(chosen.isEmpty())return@setPositiveButton;val input=EditText(context).apply{hint="Folder name"};AlertDialog.Builder(context).setTitle("Name folder").setView(input).setNegativeButton("Cancel",null).setPositiveButton("Save"){_,_->folders.save(AetherFolder(UUID.randomUUID().toString(),input.text.toString().trim().ifBlank{"Folder"},chosen));invalidate()}.show()}.show()}
 private fun quickTap(y:Float){when(((y-106*d)/(66*d)).toInt()){0->AetherSystemActions.launchHome(context);1->tool("notes");2->tool("voice");3->tool("calculator");4->tool("screenshot");5->tool("clipboard");6->context.startActivity(Intent(context,AetherWidgetHostActivity::class.java));7->context.startActivity(Intent(context,AetherSettingsActivity::class.java))}}
 private fun tool(name:String){context.startActivity(Intent(context,AetherToolsActivity::class.java).putExtra(AetherToolsActivity.EXTRA_TOOL,name))}
 private fun controlTap(x:Float,y:Float){when(((y-104*d)/(70*d)).toInt()*2+(if(x<width/2)0 else 1)){0->AetherSystemActions.openWifi(context);1->AetherSystemActions.openBluetooth(context);2->AetherSystemActions.openAirplane(context);3->AetherSystemActions.toggleRotation(context);4->AetherSystemActions.toggleTorch(context);5->AetherSystemActions.adjustBrightness(context,10);6->AetherSystemActions.adjustBrightness(context,-10);7->AetherSystemActions.toggleDnd(context);8->AetherSystemActions.openSettings(context)}}
 private fun multiTap(y:Float){val list=history.load().mapNotNull{h->apps.firstOrNull{it.packageName==h.packageName}}.distinctBy{it.packageName};val i=((y-108*d)/(84*d)).toInt();if(i in list.indices)AetherSystemActions.launchAdjacent(context,list[i].packageName)}
 private fun setupTap(y:Float){when(((y-110*d)/(68*d)).toInt()){0->context.startActivity(Intent(Settings.ACTION_HOME_SETTINGS));1->context.startActivity(Intent(Settings.ACTION_MANAGE_OVERLAY_PERMISSION).setData(android.net.Uri.parse("package:${context.packageName}")));2->AetherSystemActions.openNotificationAccess(context);3->context.startActivity(Intent(Settings.ACTION_ACCESSIBILITY_SETTINGS));4->AetherSystemActions.requestWriteSettings(context);5->context.startActivity(Intent(context,AetherSettingsActivity::class.java))}}
}
