package com.aether.launcher.ui

import android.app.Activity
import android.content.Context
import android.content.Intent
import android.graphics.Canvas
import android.graphics.Color
import android.graphics.Paint
import android.graphics.RectF
import android.graphics.drawable.Drawable
import android.os.Bundle
import android.provider.Settings
import android.view.MotionEvent
import android.view.View
import androidx.dynamicanimation.animation.DynamicAnimation
import androidx.dynamicanimation.animation.SpringAnimation
import androidx.dynamicanimation.animation.SpringForce
import com.aether.launcher.AetherHistoryStore
import com.aether.launcher.AetherRuntime
import com.aether.launcher.settings.AetherSettingsActivity
import com.aether.launcher.system.AetherSystemActions
import kotlin.math.abs

object AetherSurface { const val DRAWER="drawer";const val HISTORY="history";const val QUICK="quick";const val CONTROL="control";const val NOTIFICATIONS="notifications";const val WIDGETS="widgets";const val FOLDER="folder";const val MULTITASK="multitask";const val SETUP_CENTER="setup_center";const val ABOUT="about" }

class AetherSurfaceActivity:Activity(){override fun onCreate(state:Bundle?){super.onCreate(state);AetherRuntime.initialize(applicationContext);val root=AetherGlassRoot(this);root.attach(AetherSurfaceView(this,intent.getStringExtra("surface")?:AetherSurface.DRAWER,intent.getStringExtra("title")));setContentView(root)}}

class AetherSurfaceView(context:Context,private val surface:String,private val incomingTitle:String?):View(context){
 private val p=Paint(Paint.ANTI_ALIAS_FLAG);private var downX=0f;private var downY=0f;private val apps get()=AetherRuntime.registry.launcher.apps();private val history by lazy{AetherHistoryStore(context)};private val d get()=resources.displayMetrics.density
 private val enterSpring=SpringAnimation(this,DynamicAnimation.TRANSLATION_Y)
 init{setLayerType(View.LAYER_TYPE_SOFTWARE,null);translationY=18f*d;enterSpring.spring=SpringForce(0f).apply{stiffness=520f;dampingRatio=.8f};enterSpring.start()}
 override fun onDraw(c:Canvas){val w=width.toFloat();val h=height.toFloat();p.textAlign=Paint.Align.LEFT;p.color=0x52141820;c.drawRect(0f,0f,w,h,p);p.color=Color.WHITE;p.textSize=28f*d;p.typeface=android.graphics.Typeface.DEFAULT_BOLD;c.drawText(title(),24f*d,54f*d,p);p.typeface=android.graphics.Typeface.DEFAULT;p.color=0xB8FFFFFF.toInt();p.textSize=12f*d;c.drawText(subtitle(),24f*d,76f*d,p);when(surface){AetherSurface.DRAWER->grid(c,w,h,apps,4);AetherSurface.HISTORY->history(c,w,h);AetherSurface.QUICK->quick(c,w,h);AetherSurface.CONTROL->control(c,w,h);AetherSurface.NOTIFICATIONS->notifications(c,w,h);AetherSurface.WIDGETS->widgets(c,w,h);AetherSurface.FOLDER->grid(c,w,h,apps.take(18),3);AetherSurface.MULTITASK->multitask(c,w,h);AetherSurface.SETUP_CENTER->setupCenter(c,w,h);else->about(c,w,h)}}
 private fun title()=when(surface){AetherSurface.DRAWER->"App Drawer";AetherSurface.HISTORY->"History";AetherSurface.QUICK->"Quick Space";AetherSurface.CONTROL->"Control Center";AetherSurface.NOTIFICATIONS->"Notifications";AetherSurface.WIDGETS->"Live Widgets";AetherSurface.FOLDER->incomingTitle?:"Folder";AetherSurface.MULTITASK->"Aether Multitask";AetherSurface.SETUP_CENTER->"Setup Center";else->"About Aether"}
 private fun subtitle()=when(surface){AetherSurface.DRAWER->"Installed apps • live package data";AetherSurface.HISTORY->"Recently launched";AetherSurface.QUICK->"Real tools • OS-backed actions";AetherSurface.CONTROL->"System-backed controls";AetherSurface.NOTIFICATIONS->"Notification Access data";AetherSurface.WIDGETS->"Real Android AppWidget providers";AetherSurface.MULTITASK->"Android multi-window where supported";else->""}
 private fun glass(c:Canvas,r:RectF,radius:Float){p.color=0xB7161B22.toInt();p.setShadowLayer(18f*d,0f,10f*d,0x70000000);c.drawRoundRect(r,radius,radius,p);p.clearShadowLayer();p.color=0x3AFFFFFF;c.drawRoundRect(RectF(r.left+1,r.top+1,r.right-1,r.bottom-1),radius,radius,p)}
 private fun grid(c:Canvas,w:Float,h:Float,list:List<com.aether.launcher.engine.launcher.AppInfo>,cols:Int){val gap=12f*d;val left=22f*d;val top=106f*d;val cell=(w-left*2-gap*(cols-1))/cols;val size=48f*d;list.take(48).forEachIndexed{i,a->{val col=i%cols;val row=i/cols;val x=left+col*(cell+gap);val y=top+row*82f*d;glass(c,RectF(x,y,x+cell,y+64f*d),20f*d);drawIcon(c,a.packageName,RectF(x+cell/2-size/2,y+7*d,x+cell/2+size/2,y+7*d+size));p.color=Color.WHITE;p.textAlign=Paint.Align.CENTER;p.textSize=10f*d;c.drawText(a.label.take(12),x+cell/2,y+79f*d,p)}}}
 private fun history(c:Canvas,w:Float,h:Float){val entries=history.load();val items=entries.mapNotNull{e->apps.firstOrNull{it.packageName==e.packageName}}.distinctBy{it.packageName}.take(12);if(items.isEmpty()){p.color=0xBFFFFFFF.toInt();p.textSize=15f*d;p.textAlign=Paint.Align.LEFT;c.drawText("No launch history yet.",28f*d,120f*d,p)}else grid(c,w,h,items,3)}
 private fun quick(c:Canvas,w:Float,h:Float){val actions=listOf("Home" to "Return to Aether Home","Notes" to "Save a note","Voice" to "Record from microphone","Calculator" to "Evaluate an expression","Screenshot" to "Capture the screen with user consent","Clipboard" to "Read current clipboard","Widgets" to "Add a real Android widget","Settings" to "Open Aether Settings");actions.forEachIndexed{i,a->{val y=106f*d+i*66f*d;glass(c,RectF(24f*d,y,w-24f*d,y+54f*d),18f*d);p.color=Color.WHITE;p.textSize=14f*d;p.textAlign=Paint.Align.LEFT;c.drawText(a.first,42f*d,y+23f*d,p);p.color=0xBFFFFFFF.toInt();p.textSize=10f*d;c.drawText(a.second,42f*d,y+41f*d,p)}}}
 private fun control(c:Canvas,w:Float,h:Float){val actions=listOf("Wi-Fi","Bluetooth","Airplane","Rotation","Flashlight","Brightness +","Brightness −","DND","System settings");actions.forEachIndexed{i,label->{val col=i%2;val row=i/2;val x=24f*d+col*w*.47f;val y=104f*d+row*70f*d;glass(c,RectF(x,y,x+w*.43f,y+58f*d),18f*d);p.color=Color.WHITE;p.textSize=13f*d;c.drawText(label,x+16f*d,y+31f*d,p)}}}
 private fun notifications(c:Canvas,w:Float,h:Float){val items=AetherRuntime.registry.notifications.all();if(items.isEmpty()){p.color=0xBFFFFFFF.toInt();p.textSize=14f*d;c.drawText("Enable Notification Access to populate this surface.",24f*d,120f*d,p);return};items.take(10).forEachIndexed{i,n->{val y=104f*d+i*78f*d;glass(c,RectF(22f*d,y,w-22f*d,y+66f*d),20f*d);p.color=Color.WHITE;p.textSize=13f*d;c.drawText(n.title.ifBlank{"Notification"},38f*d,y+24f*d,p);p.color=0xBFFFFFFF.toInt();p.textSize=11f*d;c.drawText(n.text.take(70),38f*d,y+43f*d,p)}}}
 private fun widgets(c:Canvas,w:Float,h:Float){glass(c,RectF(24f*d,106f*d,w-24f*d,198f*d),26f*d);p.color=Color.WHITE;p.textSize=18f*d;c.drawText("Live Android widgets",44f*d,146f*d,p);p.color=0xBFFFFFFF.toInt();p.textSize=12f*d;c.drawText("Providers, configuration and updates come from Android.",44f*d,169f*d,p);glass(c,RectF(24f*d,216f*d,w-24f*d,280f*d),22f*d);p.color=Color.WHITE;p.textSize=15f*d;c.drawText("＋  Add widget",44f*d,255f*d,p)}
 private fun multitask(c:Canvas,w:Float,h:Float){val entries=history.load().mapNotNull{e->apps.firstOrNull{it.packageName==e.packageName}}.distinctBy{it.packageName}.take(4);entries.forEachIndexed{i,a->{val y=108f*d+i*84f*d;glass(c,RectF(24f*d,y,w-24f*d,y+70f*d),20f*d);drawIcon(c,a.packageName,RectF(40f*d,y+11f*d,86f*d,y+57f*d));p.color=Color.WHITE;p.textSize=13f*d;c.drawText(a.label,100f*d,y+29f*d,p);p.color=0xBFFFFFFF.toInt();p.textSize=10f*d;c.drawText("Launch",100f*d,y+49f*d,p)}};p.color=0xAFFFFFFF.toInt();p.textSize=10f*d;c.drawText("Android decides whether split/floating placement is permitted for each app.",24f*d,h*.84f,p)}
 private fun setupCenter(c:Canvas,w:Float,h:Float){val labels=listOf("Default launcher","Overlay permission","Notification access","Accessibility","Write system settings","Aether Settings");labels.forEachIndexed{i,l->{val y=110f*d+i*68f*d;glass(c,RectF(22f*d,y,w-22f*d,y+56f*d),18f*d);p.color=Color.WHITE;p.textSize=13f*d;c.drawText(l,40f*d,y+30f*d,p)}}}
 private fun about(c:Canvas,w:Float,h:Float){glass(c,RectF(26f*d,130f*d,w-26f*d,h-120f*d),32f*d);p.color=Color.WHITE;p.textAlign=Paint.Align.CENTER;p.textSize=56f*d;c.drawText("A",w/2,230f*d,p);p.textSize=20f*d;c.drawText("AETHER",w/2,270f*d,p);p.color=0xBFFFFFFF.toInt();p.textSize=12f*d;c.drawText("Android launcher + interaction layer",w/2,300f*d,p);c.drawText("Real OS APIs • adaptive surfaces • persistent history",w/2,322f*d,p);p.textAlign=Paint.Align.LEFT}
 private fun drawIcon(c:Canvas,pkg:String,r:RectF){AetherRuntime.registry.launcher.icon(pkg)?.let{icon:Drawable->icon.setBounds(r.left.toInt(),r.top.toInt(),r.right.toInt(),r.bottom.toInt());icon.draw(c)}}
 override fun onTouchEvent(e:MotionEvent):Boolean{if(e.actionMasked==MotionEvent.ACTION_DOWN){downX=e.x;downY=e.y;return true};if(e.actionMasked==MotionEvent.ACTION_UP){val dx=e.x-downX;val dy=e.y-downY;if(abs(dx)>80f*d||abs(dy)>80f*d){(context as? Activity)?.finish();return true};when(surface){AetherSurface.DRAWER->if(downY>96f*d)launchGrid(e.x,e.y,4);AetherSurface.HISTORY->if(downY>96f*d)launchHistory(e.x,e.y);AetherSurface.QUICK->quickTap(e.y);AetherSurface.CONTROL->controlTap(e.x,e.y);AetherSurface.WIDGETS->if(downY>210f*d)context.startActivity(Intent(context,AetherWidgetHostActivity::class.java));AetherSurface.MULTITASK->multiTap(e.y);AetherSurface.SETUP_CENTER->setupTap(e.y)};return true};return true}
 private fun launchGrid(x:Float,y:Float,cols:Int){val gap=12f*d;val left=22f*d;val cell=(width-left*2-gap*(cols-1))/cols;val row=((y-106f*d)/(82f*d)).toInt();val col=((x-left)/(cell+gap)).toInt();val i=row*cols+col;if(i in apps.indices){history.record(apps[i].packageName);AetherRuntime.registry.launcher.launchIntent(apps[i].packageName)?.let{context.startActivity(it)}}}
 private fun launchHistory(x:Float,y:Float){val e=history.load().distinctBy{it.packageName};val row=((y-106f*d)/(82f*d)).toInt();val col=((x-22f*d)/((width-44f*d)/3f)).toInt();val i=row*3+col;if(i in e.indices){history.record(e[i].packageName);AetherRuntime.registry.launcher.launchIntent(e[i].packageName)?.let{context.startActivity(it)}}}
 private fun quickTap(y:Float){val i=((y-106f*d)/(66f*d)).toInt();val tool=listOf("home","notes","voice","calculator","screenshot","clipboard","widgets","settings").getOrNull(i)?:return;when(tool){"home"->AetherSystemActions.launchHome(context);"widgets"->context.startActivity(Intent(context,AetherWidgetHostActivity::class.java));"settings"->context.startActivity(Intent(context,AetherSettingsActivity::class.java));else->context.startActivity(Intent(context,AetherToolsActivity::class.java).putExtra(AetherToolsActivity.EXTRA_TOOL,tool))}}
 private fun controlTap(x:Float,y:Float){val i=((y-104f*d)/(70f*d)).toInt()*2+(if(x<width/2)0 else 1);when(i){0->AetherSystemActions.openWifi(context);1->AetherSystemActions.openBluetooth(context);2->AetherSystemActions.openAirplane(context);3->AetherSystemActions.toggleRotation(context);4->AetherSystemActions.toggleTorch(context);5->AetherSystemActions.adjustBrightness(context,10);6->AetherSystemActions.adjustBrightness(context,-10);7->AetherSystemActions.toggleDnd(context);8->AetherSystemActions.openSettings(context)}}
 private fun multiTap(y:Float){val i=((y-108f*d)/(84f*d)).toInt();val e=history.load().mapNotNull{h->apps.firstOrNull{it.packageName==h.packageName}}.distinctBy{it.packageName};if(i in e.indices)AetherSystemActions.launchPackage(context,e[i].packageName)}
 private fun setupTap(y:Float){when(((y-110f*d)/(68f*d)).toInt()){0->context.startActivity(Intent(Settings.ACTION_HOME_SETTINGS));1->context.startActivity(Intent(Settings.ACTION_MANAGE_OVERLAY_PERMISSION).setData(android.net.Uri.parse("package:${context.packageName}")));2->AetherSystemActions.openNotificationAccess(context);3->context.startActivity(Intent(Settings.ACTION_ACCESSIBILITY_SETTINGS));4->AetherSystemActions.requestWriteSettings(context);5->context.startActivity(Intent(context,AetherSettingsActivity::class.java))}}
}
