package com.aether.launcher.settings

import android.app.WallpaperManager
import android.content.Context
import android.content.Intent
import android.graphics.Color
import android.graphics.RenderEffect
import android.graphics.Shader
import android.graphics.drawable.ColorDrawable
import android.graphics.drawable.GradientDrawable
import android.net.Uri
import android.os.Build
import android.provider.Settings
import android.view.Gravity
import android.view.View
import android.widget.*
import com.aether.launcher.AetherRuntime

class AetherSettingsView(context: Context) : FrameLayout(context) {
 private val store=AetherSettingsStore(context)
 private var s=store.load()
 private var page:String?=null
 private val density get()=resources.displayMetrics.density
 private val scroll=ScrollView(context)
 private val root=LinearLayout(context).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(20),dp(26),dp(20),dp(42));setBackgroundColor(Color.TRANSPARENT)}
 init{
  clipChildren=false
  addView(WallpaperBackground(context),LayoutParams(-1,-1))
  scroll.setFillViewport(true);scroll.setBackgroundColor(Color.TRANSPARENT);scroll.addView(root);addView(scroll,LayoutParams(-1,-1))
  render()
 }
 private fun render(){root.removeAllViews();if(page==null)home()else detail(page!!)}
 private fun home(){header("Aether Settings","A quiet control surface for the entire experience.");panel("${s.homeMode.name.replace('_',' ')} • ${s.grid.columns}×${s.grid.rows}\nGlass ${s.glass.opacity}% • Dock ${s.dock.appCount}\nIsland ${on(s.island.enabled)} • Quick Space ${on(s.quickSpace.enabled)} • App Lock ${on(s.security.appLockEnabled)}")
  group("Personalize");card("Home","Launcher mode","home");card("Grid & Icons","Density, spacing, labels and folders","grid");card("Dock","Favorites count and appearance","dock");card("Glass & Appearance","Material, blur and theme","appearance");card("Motion","Springs and gestures","motion")
  group("Features");card("Dynamic Island","Live activity surface","island");card("Quick Space","Edge tools","quick");card("Control Center","System panel","control");card("Floating Windows","Window behavior","windows");card("Split Screen","Ratios and snapping","split");card("Security","App lock","security")
  group("System");card("Permissions & Access","Android permissions","permissions");card("Reset","Restore feature defaults","reset")
 }
 private fun detail(k:String){header(k.replaceFirstChar{it.uppercase()},"Aether Settings  •  tap Back to return");when(k){
  "home"->choice("Home mode",HomeMode.values().toList(),s.homeMode){s=s.copy(homeMode=it);save()}
  "grid"->{num("Columns",4,9,s.grid.columns){v->s=s.copy(grid=s.grid.copy(columns=v));save()};num("Rows",4,9,s.grid.rows){v->s=s.copy(grid=s.grid.copy(rows=v));save()};num("Icon size",34,72,s.grid.iconSize){v->s=s.copy(grid=s.grid.copy(iconSize=v));save()};num("Horizontal spacing",4,28,s.grid.horizontalSpacing){v->s=s.copy(grid=s.grid.copy(horizontalSpacing=v));save()};num("Vertical spacing",6,32,s.grid.verticalSpacing){v->s=s.copy(grid=s.grid.copy(verticalSpacing=v));save()};num("Horizontal padding",8,40,s.grid.horizontalPadding){v->s=s.copy(grid=s.grid.copy(horizontalPadding=v));save()};num("Vertical padding",8,48,s.grid.verticalPadding){v->s=s.copy(grid=s.grid.copy(verticalPadding=v));save()};toggle("Show labels",s.grid.showLabels){s=s.copy(grid=s.grid.copy(showLabels=it));save()};num("Label size",9,16,s.grid.labelSize){v->s=s.copy(grid=s.grid.copy(labelSize=v));save()};choice("Folder style",FolderStyle.values().toList(),s.grid.folderStyle){s=s.copy(grid=s.grid.copy(folderStyle=it));save()};num("Folder radius",8,40,s.grid.folderRadius){v->s=s.copy(grid=s.grid.copy(folderRadius=v));save()}}
  "dock"->{toggle("Dock enabled",s.dock.enabled){s=s.copy(dock=s.dock.copy(enabled=it));save()};num("Dock favorites",3,8,s.dock.appCount){v->s=s.copy(dock=s.dock.copy(appCount=v));save()};num("Dock height",56,110,s.dock.height){v->s=s.copy(dock=s.dock.copy(height=v));save()};num("Dock radius",12,44,s.dock.radius){v->s=s.copy(dock=s.dock.copy(radius=v));save()};toggle("Smart groups",s.dock.smartGroups){s=s.copy(dock=s.dock.copy(smartGroups=it));save()};toggle("Group by company",s.dock.groupByCompany){s=s.copy(dock=s.dock.copy(groupByCompany=it));save()};toggle("Group by category",s.dock.groupByCategory){s=s.copy(dock=s.dock.copy(groupByCategory=it));save()}}
  "appearance"->{choice("Theme",AppearanceTheme.values().toList(),s.appearance.theme){s=s.copy(appearance=s.appearance.copy(theme=it));save()};num("Glass opacity",45,100,s.glass.opacity){v->s=s.copy(glass=s.glass.copy(opacity=v));save()};num("Blur",0,50,s.glass.blur){v->s=s.copy(glass=s.glass.copy(blur=v));save()};num("Saturation",80,135,s.glass.saturation){v->s=s.copy(glass=s.glass.copy(saturation=v));save()};num("Refraction",0,40,s.glass.refraction){v->s=s.copy(glass=s.glass.copy(refraction=v));save()};num("Highlights",0,100,s.glass.highlight){v->s=s.copy(glass=s.glass.copy(highlight=v));save()};num("Depth",0,20,s.glass.depth){v->s=s.copy(glass=s.glass.copy(depth=v));save()};num("Corner radius",8,42,s.glass.cornerRadius){v->s=s.copy(glass=s.glass.copy(cornerRadius=v));save()};num("Wallpaper dim",0,40,s.appearance.wallpaperDim){v->s=s.copy(appearance=s.appearance.copy(wallpaperDim=v));save()};toggle("Show time",s.appearance.showTime){s=s.copy(appearance=s.appearance.copy(showTime=it));save()};toggle("Show AETHER label",s.appearance.showAetherLabel){s=s.copy(appearance=s.appearance.copy(showAetherLabel=it));save()}}
  "motion"->{choice("Preset",MotionPreset.values().toList(),s.motion.preset){s=s.copy(motion=s.motion.copy(preset=it));save()};num("Speed",50,160,s.motion.speed){v->s=s.copy(motion=s.motion.copy(speed=v));save()};num("Spring strength",150,800,s.motion.springStrength){v->s=s.copy(motion=s.motion.copy(springStrength=v));save()};num("Damping",10,80,s.motion.damping){v->s=s.copy(motion=s.motion.copy(damping=v));save()};num("Bounce",0,40,s.motion.bounce){v->s=s.copy(motion=s.motion.copy(bounce=v));save()};num("Gesture sensitivity",10,100,s.motion.gestureSensitivity){v->s=s.copy(motion=s.motion.copy(gestureSensitivity=v));save()}}
  "island"->{toggle("Enabled",s.island.enabled){s=s.copy(island=s.island.copy(enabled=it));save()};toggle("Cutout aware",s.island.cutoutAware){s=s.copy(island=s.island.copy(cutoutAware=it));save()};num("Width",72,180,s.island.width){v->s=s.copy(island=s.island.copy(width=v));save()};num("Height",24,70,s.island.height){v->s=s.copy(island=s.island.copy(height=v));save()};num("Corner radius",8,35,s.island.radius){v->s=s.copy(island=s.island.copy(radius=v));save()};num("Top offset",0,40,s.island.topOffset){v->s=s.copy(island=s.island.copy(topOffset=v));save()};toggle("Notifications",s.island.showNotifications){s=s.copy(island=s.island.copy(showNotifications=it));save()};toggle("Media",s.island.showMedia){s=s.copy(island=s.island.copy(showMedia=it));save()};toggle("Calls",s.island.showCalls){s=s.copy(island=s.island.copy(showCalls=it));save()};toggle("Timers",s.island.showTimers){s=s.copy(island=s.island.copy(showTimers=it));save()};toggle("Recording",s.island.showRecording){s=s.copy(island=s.island.copy(showRecording=it));save()};toggle("Navigation",s.island.showNavigation){s=s.copy(island=s.island.copy(showNavigation=it));save()}}
  "quick"->{toggle("Enabled",s.quickSpace.enabled){s=s.copy(quickSpace=s.quickSpace.copy(enabled=it));save()};choice("Edge",QuickEdge.values().toList(),s.quickSpace.edge){s=s.copy(quickSpace=s.quickSpace.copy(edge=it));save()};num("Handle thickness",3,12,s.quickSpace.handleThickness){v->s=s.copy(quickSpace=s.quickSpace.copy(handleThickness=v));save()};num("Handle length",24,90,s.quickSpace.handleLength){v->s=s.copy(quickSpace=s.quickSpace.copy(handleLength=v));save()};num("Trigger distance",40,180,s.quickSpace.triggerDistance){v->s=s.copy(quickSpace=s.quickSpace.copy(triggerDistance=v));save()};num("Sensitivity",10,100,s.quickSpace.sensitivity){v->s=s.copy(quickSpace=s.quickSpace.copy(sensitivity=v));save()};toggle("Notes",s.quickSpace.notes){s=s.copy(quickSpace=s.quickSpace.copy(notes=it));save()};toggle("Voice recorder",s.quickSpace.recorder){s=s.copy(quickSpace=s.quickSpace.copy(recorder=it));save()};toggle("Calculator",s.quickSpace.calculator){s=s.copy(quickSpace=s.quickSpace.copy(calculator=it));save()};toggle("Screenshot",s.quickSpace.screenshot){s=s.copy(quickSpace=s.quickSpace.copy(screenshot=it));save()};toggle("Clipboard",s.quickSpace.clipboard){s=s.copy(quickSpace=s.quickSpace.copy(clipboard=it));save()};toggle("Recent apps",s.quickSpace.recentApps){s=s.copy(quickSpace=s.quickSpace.copy(recentApps=it));save()}}
  "control"->{toggle("Enabled",s.controlCenter.enabled){s=s.copy(controlCenter=s.controlCenter.copy(enabled=it));save()};choice("Gesture corner",ControlEdge.values().toList(),s.controlCenter.edge){s=s.copy(controlCenter=s.controlCenter.copy(edge=it));save()};num("Tile columns",1,4,s.controlCenter.columns){v->s=s.copy(controlCenter=s.controlCenter.copy(columns=v));save()};num("Tile radius",10,40,s.controlCenter.tileRadius){v->s=s.copy(controlCenter=s.controlCenter.copy(tileRadius=v));save()};num("Panel radius",12,44,s.controlCenter.panelRadius){v->s=s.copy(controlCenter=s.controlCenter.copy(panelRadius=v));save()};toggle("Brightness",s.controlCenter.showBrightness){s=s.copy(controlCenter=s.controlCenter.copy(showBrightness=it));save()};toggle("Volume",s.controlCenter.showVolume){s=s.copy(controlCenter=s.controlCenter.copy(showVolume=it));save()};toggle("Wi-Fi",s.controlCenter.showWifi){s=s.copy(controlCenter=s.controlCenter.copy(showWifi=it));save()};toggle("Bluetooth",s.controlCenter.showBluetooth){s=s.copy(controlCenter=s.controlCenter.copy(showBluetooth=it));save()};toggle("Airplane",s.controlCenter.showAirplane){s=s.copy(controlCenter=s.controlCenter.copy(showAirplane=it));save()};toggle("Rotation",s.controlCenter.showRotation){s=s.copy(controlCenter=s.controlCenter.copy(showRotation=it));save()};toggle("Flashlight",s.controlCenter.showFlashlight){s=s.copy(controlCenter=s.controlCenter.copy(showFlashlight=it));save()};toggle("DND",s.controlCenter.showDnd){s=s.copy(controlCenter=s.controlCenter.copy(showDnd=it));save()}}
  "windows"->{toggle("Enabled",s.floatingWindows.enabled){s=s.copy(floatingWindows=s.floatingWindows.copy(enabled=it));save()};num("Default width",50,95,s.floatingWindows.defaultWidth){v->s=s.copy(floatingWindows=s.floatingWindows.copy(defaultWidth=v));save()};num("Default height",40,90,s.floatingWindows.defaultHeight){v->s=s.copy(floatingWindows=s.floatingWindows.copy(defaultHeight=v));save()};num("Radius",10,42,s.floatingWindows.radius){v->s=s.copy(floatingWindows=s.floatingWindows.copy(radius=v));save()};num("Opacity",55,100,s.floatingWindows.transparency){v->s=s.copy(floatingWindows=s.floatingWindows.copy(transparency=v));save()};num("Maximum windows",1,6,s.floatingWindows.maxWindows){v->s=s.copy(floatingWindows=s.floatingWindows.copy(maxWindows=v));save()};toggle("Resize edges",s.floatingWindows.edgeResize){s=s.copy(floatingWindows=s.floatingWindows.copy(edgeResize=it));save()};toggle("Resize corners",s.floatingWindows.cornerResize){s=s.copy(floatingWindows=s.floatingWindows.copy(cornerResize=it));save()};toggle("Snap windows",s.floatingWindows.snapWindows){s=s.copy(floatingWindows=s.floatingWindows.copy(snapWindows=it));save()};toggle("Remember positions",s.floatingWindows.rememberPositions){s=s.copy(floatingWindows=s.floatingWindows.copy(rememberPositions=it));save()}}
  "split"->{toggle("Enabled",s.splitScreen.enabled){s=s.copy(splitScreen=s.splitScreen.copy(enabled=it));save()};num("Default ratio",30,70,s.splitScreen.defaultRatio){v->s=s.copy(splitScreen=s.splitScreen.copy(defaultRatio=v));save()};toggle("Custom ratio",s.splitScreen.allowCustomRatio){s=s.copy(splitScreen=s.splitScreen.copy(allowCustomRatio=it));save()};toggle("Remember layouts",s.splitScreen.rememberLayouts){s=s.copy(splitScreen=s.splitScreen.copy(rememberLayouts=it));save()};toggle("Snap divider",s.splitScreen.snapToEdges){s=s.copy(splitScreen=s.splitScreen.copy(snapToEdges=it));save()};num("Divider thickness",2,12,s.splitScreen.dividerThickness){v->s=s.copy(splitScreen=s.splitScreen.copy(dividerThickness=v));save()}}
  "security"->{toggle("App Lock",s.security.appLockEnabled){s=s.copy(security=s.security.copy(appLockEnabled=it));save()};toggle("Relock on leave",s.security.relockOnLeave){s=s.copy(security=s.security.copy(relockOnLeave=it));save()};toggle("Relock on screen off",s.security.relockOnScreenOff){s=s.copy(security=s.security.copy(relockOnScreenOff=it));save()};num("Relock timeout",0,300,s.security.relockTimeoutSeconds){v->s=s.copy(security=s.security.copy(relockTimeoutSeconds=v));save()};toggle("Biometrics",s.security.useBiometrics){s=s.copy(security=s.security.copy(useBiometrics=it));save()};toggle("Device credential",s.security.useDeviceCredential){s=s.copy(security=s.security.copy(useDeviceCredential=it));save()};toggle("Hide locked apps",s.security.hideLockedApps){s=s.copy(security=s.security.copy(hideLockedApps=it));save()};root.addView(label("Protected apps"));AetherRuntime.registry.launcher.apps().sortedBy{it.label.lowercase()}.forEach{a->check(a.label,AetherRuntime.security.protectedApps().contains(a.packageName)){v->if(v)AetherRuntime.security.protect(a.packageName)else AetherRuntime.security.unprotect(a.packageName)}}}
  "permissions"->{action("Default launcher","Choose Aether as Home"){context.startActivity(Intent(Settings.ACTION_HOME_SETTINGS))};action("Overlay","Allow Edge Space and Island"){context.startActivity(Intent(Settings.ACTION_MANAGE_OVERLAY_PERMISSION,Uri.parse("package:${context.packageName}")))};action("Notification access","Feed live notifications"){context.startActivity(Intent("android.settings.ACTION_NOTIFICATION_LISTENER_SETTINGS"))};action("Accessibility","Foreground sensing and app lock"){context.startActivity(Intent(Settings.ACTION_ACCESSIBILITY_SETTINGS))};action("Write settings","Brightness, rotation and DND"){context.startActivity(Intent(Settings.ACTION_MANAGE_WRITE_SETTINGS,Uri.parse("package:${context.packageName}")))}}
  "reset"->{panel("Reset layout and feature preferences. History, notes and protected apps stay separate.");action("Reset Aether","Start setup again"){store.resetSetup();Toast.makeText(context,"Aether reset. Reopen the launcher.",Toast.LENGTH_LONG).show()}}
 }}
 private fun header(t:String,sub:String){val r=LinearLayout(context).apply{gravity=Gravity.CENTER_VERTICAL};if(page!=null)r.addView(glassButton("‹",52){page=null;render()},LinearLayout.LayoutParams(dp(54),dp(54)));val q=LinearLayout(context).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(10),0,0,0)};q.addView(TextView(context).apply{text=t;textSize=30f;setTextColor(Color.WHITE);typeface=android.graphics.Typeface.DEFAULT_BOLD});q.addView(TextView(context).apply{text=sub;textSize=13f;setTextColor(0xCFFFFFFF.toInt())});r.addView(q,LinearLayout.LayoutParams(0,-2,1f));root.addView(r,LinearLayout.LayoutParams(-1,dp(84)))}
 private fun group(t:String){root.addView(TextView(context).apply{text=t;textSize=18f;setTextColor(Color.WHITE);typeface=android.graphics.Typeface.DEFAULT_BOLD;setPadding(dp(4),dp(10),0,dp(4))},LinearLayout.LayoutParams(-1,dp(48)))}
 private fun card(t:String,b:String,k:String){root.addView(glassButton("$t\n$b",70){page=k;render()},LinearLayout.LayoutParams(-1,dp(70)).apply{bottomMargin=dp(8)})}
 private fun panel(t:String){val v=TextView(context).apply{text=t;textSize=13f;setTextColor(Color.WHITE);setPadding(dp(18),dp(14),dp(18),dp(14));background=glassDrawable(0x3AFFFFFF.toInt(),26f)};root.addView(v,LinearLayout.LayoutParams(-1,dp(92)).apply{bottomMargin=dp(12)})}
 private fun toggle(label:String,v:Boolean,a:(Boolean)->Unit){val r=LinearLayout(context).apply{gravity=Gravity.CENTER_VERTICAL;setPadding(dp(16),0,dp(8),0);background=glassDrawable(0x28FFFFFF.toInt(),22f)};r.addView(TextView(context).apply{text=label;textSize=14f;setTextColor(Color.WHITE)},LinearLayout.LayoutParams(0,dp(56),1f));r.addView(Switch(context).apply{isChecked=v;setOnCheckedChangeListener{_,x->a(x)}},LinearLayout.LayoutParams(dp(64),dp(52)));root.addView(r,LinearLayout.LayoutParams(-1,dp(60)).apply{bottomMargin=dp(6)})}
 private fun num(label:String,min:Int,max:Int,v:Int,a:(Int)->Unit){val r=LinearLayout(context).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(12),dp(6),dp(12),dp(6));background=glassDrawable(0x20FFFFFF.toInt(),20f)};val h=LinearLayout(context).apply{gravity=Gravity.CENTER_VERTICAL};val out=TextView(context).apply{text=v.toString();textSize=12f;setTextColor(0xEFFFFFFF.toInt());gravity=Gravity.END};h.addView(TextView(context).apply{text=label;textSize=14f;setTextColor(Color.WHITE)},LinearLayout.LayoutParams(0,dp(28),1f));h.addView(out,LinearLayout.LayoutParams(dp(54),dp(28)));r.addView(h);r.addView(SeekBar(context).apply{this.max=max-min;progress=(v-min).coerceIn(0,this.max);setOnSeekBarChangeListener(object:SeekBar.OnSeekBarChangeListener{override fun onProgressChanged(sb:SeekBar?,p:Int,fromUser:Boolean){val n=p+min;out.text=n.toString();if(fromUser)a(n)};override fun onStartTrackingTouch(sb:SeekBar?){ };override fun onStopTrackingTouch(sb:SeekBar?){ }})});root.addView(r,LinearLayout.LayoutParams(-1,dp(78)).apply{bottomMargin=dp(7)})}
 private fun check(label:String,v:Boolean,a:(Boolean)->Unit)=toggle(label,v,a)
 private fun <E:Enum<E>> choice(label:String,values:List<E>,selected:E,a:(E)->Unit){val r=LinearLayout(context).apply{gravity=Gravity.CENTER_VERTICAL;setPadding(dp(14),0,dp(8),0);background=glassDrawable(0x24FFFFFF.toInt(),20f)};r.addView(TextView(context).apply{text=label;textSize=14f;setTextColor(Color.WHITE)},LinearLayout.LayoutParams(0,dp(58),1f));val sp=Spinner(context);sp.adapter=ArrayAdapter(context,android.R.layout.simple_spinner_dropdown_item,values.map{it.name.replace('_',' ').lowercase().replaceFirstChar{c->c.uppercase()}});sp.setSelection(values.indexOf(selected));sp.onItemSelectedListener=object:AdapterView.OnItemSelectedListener{override fun onItemSelected(parent:AdapterView<*>?,view:View?,position:Int,id:Long){a(values[position])};override fun onNothingSelected(parent:AdapterView<*>?){}};r.addView(sp,LinearLayout.LayoutParams(dp(190),dp(58)));root.addView(r,LinearLayout.LayoutParams(-1,dp(64)).apply{bottomMargin=dp(7)})}
 private fun action(t:String,b:String,a:()->Unit)=root.addView(glassButton("$t\n$b",72){runCatching{a()}.onFailure{Toast.makeText(context,"Unavailable on this device",Toast.LENGTH_SHORT).show()}},LinearLayout.LayoutParams(-1,dp(72)).apply{bottomMargin=dp(8)})
 private fun label(t:String)=TextView(context).apply{text=t;textSize=18f;setTextColor(Color.WHITE);setPadding(0,dp(12),0,dp(8))}.also{root.addView(it,LinearLayout.LayoutParams(-1,dp(46)))}
 private fun glassButton(textValue:String,height:Int,click:()->Unit)=TextView(context).apply{text=textValue;textSize=14f;gravity=Gravity.CENTER_VERTICAL or Gravity.CENTER;setTextColor(Color.WHITE);setTypeface(android.graphics.Typeface.DEFAULT,android.graphics.Typeface.BOLD);setPadding(dp(16),0,dp(16),0);background=glassDrawable(0x3AFFFFFF.toInt(),26f);elevation=dp(3).toFloat();setOnClickListener{click()}}
 private fun glassDrawable(fill:Int,radius:Float)=GradientDrawable().apply{cornerRadius=dp(radius.toInt()).toFloat();setColor(fill);setStroke(dp(1),0x42FFFFFF)}
 private fun save(){store.save(s)}
 private fun on(v:Boolean)=if(v)"ON" else "OFF"
 private fun dp(v:Int)= (v*density).toInt()
}

private class WallpaperBackground(c:Context):View(c){private val p=android.graphics.Paint(android.graphics.Paint.ANTI_ALIAS_FLAG);private val wallpaper=runCatching{WallpaperManager.getInstance(c).drawable}.getOrElse{ColorDrawable(0xFF080A0E.toInt())};init{if(Build.VERSION.SDK_INT>=31)setRenderEffect(RenderEffect.createBlurEffect(24f,24f,Shader.TileMode.CLAMP))};override fun onDraw(c:android.graphics.Canvas){wallpaper.setBounds(0,0,width,height);wallpaper.draw(c);p.color=0x7A05080D;c.drawRect(0f,0f,width.toFloat(),height.toFloat(),p)}}
