package com.aether.launcher.settings

import android.content.Context
import android.content.Intent
import android.graphics.Color
import android.graphics.Typeface
import android.net.Uri
import android.provider.Settings
import android.view.Gravity
import android.view.View
import android.widget.*
import com.aether.launcher.AetherRuntime
import kotlin.math.roundToInt

class AetherSettingsView(context: Context) : ScrollView(context) {
    private val store = AetherSettingsStore(context)
    private var s = store.load()
    private val root = LinearLayout(context).apply { orientation = LinearLayout.VERTICAL; setPadding(dp(20), dp(28), dp(20), dp(32)) }
    private var category: String? = null
    init { setFillViewport(true); setBackgroundColor(0xFF080A0E.toInt()); addView(root); render() }
    private fun render() { root.removeAllViews(); if (category == null) home() else detail(category!!) }
    private fun home() {
        header("Aether Settings", "Every setup choice, plus advanced controls.")
        addSummary()
        section("Personalize")
        card("Home", "App placement and launcher mode", "home"); card("Grid & Icons", "Rows, columns, size, labels, folders", "grid"); card("Dock", "Apps, height, radius and smart grouping", "dock"); card("Appearance & Glass", "Theme, material, blur, refraction and depth", "appearance"); card("Motion", "Spring, speed, damping and gestures", "motion")
        section("Aether Features")
        card("Dynamic Island", "Cutout-aware live activities and notifications", "island"); card("Quick Space", "Edge handle, actions and tools", "quick"); card("Control Center", "Tiles, corner and panel layout", "control"); card("Floating Windows", "Size, resizing, snapping and limits", "windows"); card("Split Screen", "Ratios, divider and remembered layouts", "split"); card("Security & App Lock", "Protected apps and relock behavior", "security")
        section("System Setup")
        card("Permissions & Access", "Launcher, overlay, notifications, accessibility and Shizuku", "permissions"); card("Reset Setup", "Return visual and feature preferences to defaults", "reset")
    }
    private fun detail(k: String) { when(k){"home"->homeDetail();"grid"->gridDetail();"dock"->dockDetail();"appearance"->appearanceDetail();"motion"->motionDetail();"island"->islandDetail();"quick"->quickDetail();"control"->controlDetail();"windows"->windowsDetail();"split"->splitDetail();"security"->securityDetail();"permissions"->permissionsDetail();"reset"->resetDetail()} }
    private fun header(title:String, subtitle:String){ val row=LinearLayout(context).apply{gravity=Gravity.CENTER_VERTICAL;setPadding(0,0,0,dp(18))};if(category!=null)row.addView(Button(context).apply{text="‹";textSize=26f;setTextColor(Color.WHITE);setOnClickListener{category=null;render()}},LinearLayout.LayoutParams(dp(52),dp(52)));val b=LinearLayout(context).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(6),0,0,0)};b.addView(text(title,30f,Color.WHITE,true));b.addView(text(subtitle,14f,0xAFFFFFFF.toInt(),false));row.addView(b,LinearLayout.LayoutParams(0,-2,1f));root.addView(row)}
    private fun section(t:String){root.addView(text(t,19f,Color.WHITE,true),LinearLayout.LayoutParams(-1,dp(50)))}
    private fun card(t:String,d:String,k:String){root.addView(Button(context).apply{text="$t\n$d";gravity=Gravity.START or Gravity.CENTER_VERTICAL;setTextColor(Color.WHITE);textSize=14f;setPadding(dp(18),0,dp(18),0);setOnClickListener{category=k;render()}},LinearLayout.LayoutParams(-1,dp(72)).apply{bottomMargin=dp(8)})}
    private fun addSummary(){root.addView(text("${s.homeMode.name.replace('_',' ')}   •   ${s.grid.columns}×${s.grid.rows}\nGlass ${s.glass.opacity}%   •   Dock ${s.dock.appCount}\nIsland ${if(s.island.enabled)"ON" else "OFF"}   •   Quick Space ${if(s.quickSpace.enabled)"ON" else "OFF"}   •   App Lock ${if(s.security.appLockEnabled)"ON" else "OFF"}",14f,Color.WHITE,false).apply{setPadding(dp(18),dp(18),dp(18),dp(18));setBackgroundColor(0x171F2933)},LinearLayout.LayoutParams(-1,dp(92)).apply{bottomMargin=dp(14)})}
    private fun homeDetail(){header("Home","Choose how apps appear.");choice("Home mode",HomeMode.values().toList(),s.homeMode){s=s.copy(homeMode=it);save()};preview("Home preview",180)}
    private fun gridDetail(){header("Grid & Icons","Tune the home grid in detail.");slider("Apps per row",3,7,s.grid.columns){grid{s.copy(columns=it)}};slider("Rows",4,9,s.grid.rows){grid{s.copy(rows=it)}};slider("Icon size",40,72,s.grid.iconSize){grid{s.copy(iconSize=it)}};slider("Horizontal spacing",4,28,s.grid.horizontalSpacing){grid{s.copy(horizontalSpacing=it)}};slider("Vertical spacing",6,32,s.grid.verticalSpacing){grid{s.copy(verticalSpacing=it)}};slider("Horizontal padding",8,40,s.grid.horizontalPadding){grid{s.copy(horizontalPadding=it)}};slider("Vertical padding",8,48,s.grid.verticalPadding){grid{s.copy(verticalPadding=it)}};toggle("Show app labels",s.grid.showLabels){grid{s.copy(showLabels=it)}};slider("Label size",9,16,s.grid.labelSize){grid{s.copy(labelSize=it)}};choice("Folder style",FolderStyle.values().toList(),s.grid.folderStyle){grid{s.copy(folderStyle=it)}};slider("Folder corner radius",8,40,s.grid.folderRadius){grid{s.copy(folderRadius=it)}};preview("Live grid preview",160)}
    private fun dockDetail(){header("Dock","Build the bottom bar and smart groups.");toggle("Dock enabled",s.dock.enabled){dock{s.copy(enabled=it)}};slider("Dock apps",3,8,s.dock.appCount){dock{s.copy(appCount=it)}};slider("Dock height",56,110,s.dock.height){dock{s.copy(height=it)}};slider("Dock radius",12,44,s.dock.radius){dock{s.copy(radius=it)}};slider("Bottom padding",4,40,s.dock.bottomPadding){dock{s.copy(bottomPadding=it)}};toggle("Auto-group similar apps",s.dock.autoGroup){dock{s.copy(autoGroup=it)}};toggle("Group by company",s.dock.groupByCompany){dock{s.copy(groupByCompany=it)}};toggle("Group by category",s.dock.groupByCategory){dock{s.copy(groupByCategory=it)}};toggle("Smart groups",s.dock.smartGroups){dock{s.copy(smartGroups=it)}};preview("Dock preview",140)}
    private fun appearanceDetail(){header("Appearance & Glass","Tune Aether's visual material.");choice("Theme",AppearanceTheme.values().toList(),s.appearance.theme){s=s.copy(appearance=s.appearance.copy(theme=it));save()};slider("Corner radius",8,42,s.glass.cornerRadius){glass{s.copy(cornerRadius=it)}};slider("Glass opacity",45,100,s.glass.opacity){glass{s.copy(opacity=it)}};slider("Blur",0,50,s.glass.blur){glass{s.copy(blur=it)}};slider("Saturation",80,135,s.glass.saturation){glass{s.copy(saturation=it)}};slider("Refraction",0,40,s.glass.refraction){glass{s.copy(refraction=it)}};slider("Highlights",0,100,s.glass.highlight){glass{s.copy(highlight=it)}};slider("Depth",0,20,s.glass.depth){glass{s.copy(depth=it)}};slider("Border",0,100,s.glass.border){glass{s.copy(border=it)}};slider("Wallpaper dim",0,40,s.appearance.wallpaperDim){appearance{s.copy(wallpaperDim=it)}};toggle("Show time",s.appearance.showTime){appearance{s.copy(showTime=it)}};toggle("Show AETHER label",s.appearance.showAetherLabel){appearance{s.copy(showAetherLabel=it)}}}
    private fun motionDetail(){header("Motion","Tune the spring personality.");choice("Preset",MotionPreset.values().toList(),s.motion.preset){motion{s.copy(preset=it)}};slider("Speed",50,160,s.motion.speed){motion{s.copy(speed=it)}};slider("Spring strength",150,800,s.motion.springStrength){motion{s.copy(springStrength=it)}};slider("Damping",10,80,s.motion.damping){motion{s.copy(damping=it)}};slider("Bounce",0,40,s.motion.bounce){motion{s.copy(bounce=it)}};slider("Gesture sensitivity",10,100,s.motion.gestureSensitivity){motion{s.copy(gestureSensitivity=it)}};preview("Motion response",160)}
    private fun islandDetail(){header("Dynamic Island","Tune live activity behavior and geometry.");toggle("Enable Dynamic Island",s.island.enabled){island{s.copy(enabled=it)}};toggle("Adapt around camera cutout",s.island.cutoutAware){island{s.copy(cutoutAware=it)}};slider("Width",72,180,s.island.width){island{s.copy(width=it)}};slider("Height",24,70,s.island.height){island{s.copy(height=it)}};slider("Corner radius",8,35,s.island.radius){island{s.copy(radius=it)}};slider("Top offset",0,40,s.island.topOffset){island{s.copy(topOffset=it)}};toggle("Blur around cutout",s.island.blurSurroundingCutout){island{s.copy(blurSurroundingCutout=it)}};toggle("Notifications",s.island.showNotifications){island{s.copy(showNotifications=it)}};toggle("Media",s.island.showMedia){island{s.copy(showMedia=it)}};toggle("Calls",s.island.showCalls){island{s.copy(showCalls=it)}};toggle("Timers / alarms",s.island.showTimers){island{s.copy(showTimers=it)}};toggle("Recording",s.island.showRecording){island{s.copy(showRecording=it)}};toggle("Navigation",s.island.showNavigation){island{s.copy(showNavigation=it)}};preview("Island states",140)}
    private fun quickDetail(){header("Quick Space","Tune the edge handle and tools.");toggle("Enable Quick Space",s.quickSpace.enabled){quick{s.copy(enabled=it)}};choice("Edge",QuickEdge.values().toList(),s.quickSpace.edge){quick{s.copy(edge=it)}};slider("Handle thickness",3,12,s.quickSpace.handleThickness){quick{s.copy(handleThickness=it)}};slider("Handle length",24,90,s.quickSpace.handleLength){quick{s.copy(handleLength=it)}};slider("Trigger distance",40,180,s.quickSpace.triggerDistance){quick{s.copy(triggerDistance=it)}};slider("Sensitivity",10,100,s.quickSpace.sensitivity){quick{s.copy(sensitivity=it)}};slider("Panel width",70,96,s.quickSpace.panelWidth){quick{s.copy(panelWidth=it)}};slider("Panel height",28,70,s.quickSpace.panelHeight){quick{s.copy(panelHeight=it)}};toggle("Notes",s.quickSpace.notes){quick{s.copy(notes=it)}};toggle("Voice recorder",s.quickSpace.recorder){quick{s.copy(recorder=it)}};toggle("Calculator",s.quickSpace.calculator){quick{s.copy(calculator=it)}};toggle("Screenshot",s.quickSpace.screenshot){quick{s.copy(screenshot=it)}};toggle("Clipboard",s.quickSpace.clipboard){quick{s.copy(clipboard=it)}};toggle("Recent apps",s.quickSpace.recentApps){quick{s.copy(recentApps=it)}};toggle("Shortcuts",s.quickSpace.shortcuts){quick{s.copy(shortcuts=it)}}}
    private fun controlDetail(){header("Control Center","Tune the system panel.");toggle("Enable Control Center",s.controlCenter.enabled){control{s.copy(enabled=it)}};choice("Gesture corner",ControlEdge.values().toList(),s.controlCenter.edge){control{s.copy(edge=it)}};slider("Tile columns",1,4,s.controlCenter.columns){control{s.copy(columns=it)}};slider("Tile radius",10,40,s.controlCenter.tileRadius){control{s.copy(tileRadius=it)}};slider("Panel radius",12,44,s.controlCenter.panelRadius){control{s.copy(panelRadius=it)}};toggle("Brightness",s.controlCenter.showBrightness){control{s.copy(showBrightness=it)}};toggle("Volume",s.controlCenter.showVolume){control{s.copy(showVolume=it)}};toggle("Wi-Fi",s.controlCenter.showWifi){control{s.copy(showWifi=it)}};toggle("Bluetooth",s.controlCenter.showBluetooth){control{s.copy(showBluetooth=it)}};toggle("Airplane mode",s.controlCenter.showAirplane){control{s.copy(showAirplane=it)}};toggle("Rotation",s.controlCenter.showRotation){control{s.copy(showRotation=it)}};toggle("Flashlight",s.controlCenter.showFlashlight){control{s.copy(showFlashlight=it)}};toggle("Do Not Disturb",s.controlCenter.showDnd){control{s.copy(showDnd=it)}};preview("Control Center",170)}
    private fun windowsDetail(){header("Floating Windows","Configure floating window behavior.");toggle("Enable floating windows",s.floatingWindows.enabled){floating{s.copy(enabled=it)}};slider("Default width",50,95,s.floatingWindows.defaultWidth){floating{s.copy(defaultWidth=it)}};slider("Default height",40,90,s.floatingWindows.defaultHeight){floating{s.copy(defaultHeight=it)}};slider("Window radius",10,42,s.floatingWindows.radius){floating{s.copy(radius=it)}};slider("Window opacity",55,100,s.floatingWindows.transparency){floating{s.copy(transparency=it)}};slider("Shadow",0,100,s.floatingWindows.shadow){floating{s.copy(shadow=it)}};slider("Maximum windows",1,6,s.floatingWindows.maxWindows){floating{s.copy(maxWindows=it)}};toggle("Resize from edges",s.floatingWindows.edgeResize){floating{s.copy(edgeResize=it)}};toggle("Resize from corners",s.floatingWindows.cornerResize){floating{s.copy(cornerResize=it)}};toggle("Snap windows",s.floatingWindows.snapWindows){floating{s.copy(snapWindows=it)}};toggle("Remember positions",s.floatingWindows.rememberPositions){floating{s.copy(rememberPositions=it)}}}
    private fun splitDetail(){header("Split Screen","Configure split-screen behavior.");toggle("Enable split screen",s.splitScreen.enabled){split{s.copy(enabled=it)}};slider("Default ratio",30,70,s.splitScreen.defaultRatio){split{s.copy(defaultRatio=it)}};toggle("Allow custom ratios",s.splitScreen.allowCustomRatio){split{s.copy(allowCustomRatio=it)}};toggle("Remember layouts",s.splitScreen.rememberLayouts){split{s.copy(rememberLayouts=it)}};toggle("Snap divider",s.splitScreen.snapToEdges){split{s.copy(snapToEdges=it)}};slider("Divider thickness",2,12,s.splitScreen.dividerThickness){split{s.copy(dividerThickness=it)}};preview("Split ${s.splitScreen.defaultRatio}/${100-s.splitScreen.defaultRatio}",140)}
    private fun securityDetail(){header("Security & App Lock","Protect apps and choose when Aether relocks.");toggle("App Lock",s.security.appLockEnabled){security{s.copy(appLockEnabled=it)}};toggle("Relock when leaving app",s.security.relockOnLeave){security{s.copy(relockOnLeave=it)}};toggle("Relock when screen turns off",s.security.relockOnScreenOff){security{s.copy(relockOnScreenOff=it)}};slider("Relock timeout (seconds)",0,300,s.security.relockTimeoutSeconds){security{s.copy(relockTimeoutSeconds=it)}};toggle("Use biometrics",s.security.useBiometrics){security{s.copy(useBiometrics=it)}};toggle("Use device credential",s.security.useDeviceCredential){security{s.copy(useDeviceCredential=it)}};toggle("Hide locked apps",s.security.hideLockedApps){security{s.copy(hideLockedApps=it)}};root.addView(text("Protected apps",19f,Color.WHITE,true),LinearLayout.LayoutParams(-1,dp(50)));AetherRuntime.registry.launcher.apps().sortedBy{it.label.lowercase()}.forEach{app->val row=LinearLayout(context).apply{gravity=Gravity.CENTER_VERTICAL};row.addView(text(app.label,14f,Color.WHITE,false),LinearLayout.LayoutParams(0,dp(50),1f));row.addView(CheckBox(context).apply{isChecked=AetherRuntime.security.protectedApps().contains(app.packageName);setOnCheckedChangeListener{_,checked->if(checked)AetherRuntime.security.protect(app.packageName)else AetherRuntime.security.unprotect(app.packageName)}},LinearLayout.LayoutParams(dp(58),dp(50)));root.addView(row)}}
    private fun permissionsDetail(){header("Permissions & Access","Android controls these capabilities. Aether never silently grants them.");action("Default launcher","Choose Aether as your Home app"){context.startActivity(Intent(Settings.ACTION_HOME_SETTINGS))};action("Draw over other apps","Needed for floating Island and Quick Space"){context.startActivity(Intent(Settings.ACTION_MANAGE_OVERLAY_PERMISSION,Uri.parse("package:"+context.packageName)))};action("Notification access","Feeds notifications into Dynamic Island"){context.startActivity(Intent("android.settings.ACTION_NOTIFICATION_LISTENER_SETTINGS"))};action("Accessibility","Enables foreground app sensing and app-lock interception"){context.startActivity(Intent(Settings.ACTION_ACCESSIBILITY_SETTINGS))};action("Shizuku","Open Shizuku's official site and setup information"){context.startActivity(Intent(Intent.ACTION_VIEW,Uri.parse("https://shizuku.rikka.app/")))}}
    private fun resetDetail(){header("Reset Setup","Return Aether's visual and feature preferences to defaults.");action("Reset","This sends you back through the first-run setup. Protected app policies are stored separately."){AlertDialog.Builder(context).setTitle("Reset Aether?").setMessage("Your layout, appearance and feature choices will return to their defaults.").setNegativeButton("Cancel",null).setPositiveButton("Reset"){_,_->store.resetSetup();Toast.makeText(context,"Aether reset. Restart the launcher to run setup again.",Toast.LENGTH_LONG).show()}.show()}}
    private fun action(title:String,desc:String,click:()->Unit){root.addView(Button(context).apply{text="$title\n$desc";gravity=Gravity.START or Gravity.CENTER_VERTICAL;setTextColor(Color.WHITE);textSize=14f;setPadding(dp(18),0,dp(18),0);setOnClickListener{runCatching{click()}.onFailure{Toast.makeText(context,"Unavailable on this device",Toast.LENGTH_SHORT).show()}}},LinearLayout.LayoutParams(-1,dp(76)).apply{bottomMargin=dp(8)})}
    private fun <E:Enum<E>> choice(label:String,values:List<E>,selected:E,change:(E)->Unit){val row=LinearLayout(context).apply{gravity=Gravity.CENTER_VERTICAL};row.addView(text(label,14f,Color.WHITE,false),LinearLayout.LayoutParams(0,dp(56),1f));val sp=Spinner(context);sp.adapter=ArrayAdapter(context,android.R.layout.simple_spinner_dropdown_item,values.map{it.name.replace('_',' ').lowercase().replaceFirstChar{c->c.uppercase()}});sp.setSelection(values.indexOf(selected));sp.onItemSelectedListener=object:AdapterView.OnItemSelectedListener{override fun onItemSelected(p:AdapterView<*>?,v:View?,pos:Int,id:Long){change(values[pos])};override fun onNothingSelected(p:AdapterView<*>?){}};row.addView(sp,LinearLayout.LayoutParams(dp(180),dp(56)));root.addView(row)}
    private fun toggle(label:String,value:Boolean,change:(Boolean)->Unit){val row=LinearLayout(context).apply{gravity=Gravity.CENTER_VERTICAL};row.addView(text(label,14f,Color.WHITE,false),LinearLayout.LayoutParams(0,dp(54),1f));row.addView(Switch(context).apply{isChecked=value;setOnCheckedChangeListener{_,c->change(c)}},LinearLayout.LayoutParams(dp(64),dp(52)));root.addView(row)}
    private fun slider(label:String,min:Int,max:Int,value:Int,change:(Int)->Unit){val box=LinearLayout(context).apply{orientation=LinearLayout.VERTICAL;setPadding(0,dp(6),0,dp(4))};val row=LinearLayout(context).apply{gravity=Gravity.CENTER_VERTICAL};val v=text(value.toString(),12f,0xB5FFFFFF.toInt(),false);v.gravity=Gravity.END;row.addView(text(label,14f,Color.WHITE,false),LinearLayout.LayoutParams(0,dp(30),1f));row.addView(v,LinearLayout.LayoutParams(dp(54),dp(30)));box.addView(row);box.addView(SeekBar(context).apply{max=max-min;progress=(value-min).coerceIn(0,max-min);setOnSeekBarChangeListener(object:SeekBar.OnSeekBarChangeListener{override fun onProgressChanged(sb:SeekBar?,p:Int,fromUser:Boolean){val n=p+min;v.text=n.toString();if(fromUser)change(n)};override fun onStartTrackingTouch(sb:SeekBar?){};override fun onStopTrackingTouch(sb:SeekBar?) {}})});root.addView(box)}
    private fun preview(label:String,h:Int){root.addView(object:View(context){val p=android.graphics.Paint(1);override fun onDraw(c:android.graphics.Canvas){p.color=0x18212A33;c.drawRoundRect(0f,0f,width.toFloat(),h.toFloat(),28f,28f,p);p.color=0x40FFFFFF;c.drawRoundRect(12f,12f,width-12f,h-12f,22f,22f,p);p.color=Color.WHITE;p.textAlign=android.graphics.Paint.Align.CENTER;p.textSize=13f;c.drawText(label,width/2f,34f,p)}} ,LinearLayout.LayoutParams(-1,dp(h)).apply{topMargin=dp(8);bottomMargin=dp(12)})}
    private fun save(){store.save(s)}
    private fun grid(f:GridSettings.()->GridSettings){s=s.copy(grid=s.grid.f());save()};private fun dock(f:DockSettings.()->DockSettings){s=s.copy(dock=s.dock.f());save()};private fun glass(f:GlassSettings.()->GlassSettings){s=s.copy(glass=s.glass.f());save()};private fun motion(f:MotionSettings.()->MotionSettings){s=s.copy(motion=s.motion.f());save()};private fun appearance(f:AppearanceSettings.()->AppearanceSettings){s=s.copy(appearance=s.appearance.f());save()};private fun island(f:IslandSettings.()->IslandSettings){s=s.copy(island=s.island.f());save()};private fun quick(f:QuickSpaceSettings.()->QuickSpaceSettings){s=s.copy(quickSpace=s.quickSpace.f());save()};private fun control(f:ControlCenterSettings.()->ControlCenterSettings){s=s.copy(controlCenter=s.controlCenter.f());save()};private fun floating(f:FloatingWindowSettings.()->FloatingWindowSettings){s=s.copy(floatingWindows=s.floatingWindows.f());save()};private fun split(f:SplitScreenSettings.()->SplitScreenSettings){s=s.copy(splitScreen=s.splitScreen.f());save()};private fun security(f:SecuritySettings.()->SecuritySettings){s=s.copy(security=s.security.f());save()}
    private fun text(t:String,size:Float,color:Int,bold:Boolean)=TextView(context).apply{text=t;textSize=size;setTextColor(color);if(bold)typeface=Typeface.DEFAULT_BOLD}
    private fun dp(v:Int)=(v*resources.displayMetrics.density).roundToInt()
}
