package com.aether.launcher.settings

import android.app.WallpaperManager
import android.content.Context
import android.graphics.*
import android.graphics.drawable.Drawable
import android.os.Build
import android.view.*
import android.widget.*
import kotlin.math.roundToInt

class AetherSetupView(context: Context, private val onFinished: () -> Unit) : FrameLayout(context) {
    private val store=AetherSettingsStore(context); private var s=store.load(); private var page=0
    private val pages=listOf("Hello","Home","Grid","Glass","Dock","Dynamic Island","Quick Space","Control Center","Floating Windows","Split Screen","Security","Ready")
    private val content=LinearLayout(context).apply{orientation=LinearLayout.VERTICAL;gravity=Gravity.CENTER_HORIZONTAL}
    private val density=resources.displayMetrics.density
    init{addView(WallpaperBlurView(context),LayoutParams(-1,-1));addView(Scroll(context),LayoutParams(-1,-1));render()}
    private inner class Scroll(c:Context):ScrollView(c){init{isFillViewport=true;setBackgroundColor(Color.TRANSPARENT);addView(content,LayoutParams(-1,-1));content.setPadding(dp(24),dp(54),dp(24),dp(30))}}
    private fun render(){content.removeAllViews();content.addView(TextView(context).apply{text="AETHER  •  ${page+1}/${pages.size}";textSize=11f;setTextColor(0xAFFFFFFF.toInt());gravity=Gravity.CENTER},lp(-1,30));when(page){0->hello();1->home();2->grid();3->glass();4->dock();5->island();6->quick();7->control();8->windows();9->split();10->security();11->ready()};content.addView(View(context),lp(-1,18));content.addView(GlassButton(context,if(page==pages.lastIndex)"Enter Aether" else "Continue  →"){if(page==pages.lastIndex){store.save(s.copy(setupComplete=true));onFinished()}else{page++;render()}},lp(-1,62));if(page>0)content.addView(TextView(context).apply{text="‹  Back";textSize=15f;setTextColor(0xDFFFFFFF.toInt());gravity=Gravity.CENTER;setOnClickListener{page--;render()}},lp(-1,48))}
    private fun hello(){hero("hello","A new way to use Android.");content.addView(TextView(context).apply{text="AETHER";textSize=12f;letterSpacing=.35f;setTextColor(0xBFFFFFFF.toInt());gravity=Gravity.CENTER},lp(-1,50))}
    private fun home(){hero("Your home","Choose how Aether organizes your apps.");choice("All apps on Home","Every installed launcher app appears directly on your pages.",HomeMode.ALL_APPS,s.homeMode){s=s.copy(homeMode=it);save()};choice("Home + App Drawer","Clean home, then swipe up for every app.",HomeMode.HOME_AND_DRAWER,s.homeMode){s=s.copy(homeMode=it);save()};choice("App Drawer only","Minimal home with the drawer as the main app space.",HomeMode.DRAWER_ONLY,s.homeMode){s=s.copy(homeMode=it);save()};previewGrid()}
    private fun grid(){hero("Your grid","Choose density. Icons scale down naturally as the grid grows.");listOf(4 to 4,4 to 5,4 to 6,5 to 5,5 to 6,6 to 6,6 to 7,7 to 7,8 to 8,9 to 9).forEach{v->choice("${v.first} × ${v.second}","${v.first*v.second} positions",v,s.grid.columns to s.grid.rows){x->s=s.copy(grid=s.grid.copy(columns=x.first,rows=x.second,iconSize=(420/x.first).coerceIn(34,62)));save()}};toggle("App labels",s.grid.showLabels){s=s.copy(grid=s.grid.copy(showLabels=it));save()};previewGrid()}
    private fun glass(){hero("Liquid glass","Translucent, dimensional surfaces that keep the wallpaper alive.");slider("Opacity",45,100,s.glass.opacity,"%"){s=s.copy(glass=s.glass.copy(opacity=it));save()};slider("Blur",4,50,s.glass.blur," px"){s=s.copy(glass=s.glass.copy(blur=it));save()};slider("Corner radius",8,42,s.glass.cornerRadius," dp"){s=s.copy(glass=s.glass.copy(cornerRadius=it));save()};slider("Refraction",0,40,s.glass.refraction,"%"){s=s.copy(glass=s.glass.copy(refraction=it));save()};glassCard("Material preview","Soft highlights, depth and wallpaper visible through every surface.")}
    private fun dock(){hero("Your dock","Your most-used apps, always within reach.");toggle("Show dock",s.dock.enabled){s=s.copy(dock=s.dock.copy(enabled=it));save()};slider("Apps",3,8,s.dock.appCount," apps"){s=s.copy(dock=s.dock.copy(appCount=it));save()};toggle("Smart groups",s.dock.smartGroups){s=s.copy(dock=s.dock.copy(smartGroups=it));save()};toggle("Group similar companies",s.dock.groupByCompany){s=s.copy(dock=s.dock.copy(groupByCompany=it));save()};toggle("Group by category",s.dock.groupByCategory){s=s.copy(dock=s.dock.copy(groupByCategory=it));save()};glassCard("Dock preview","A floating glass surface with adaptive icon sizing and spring movement.")}
    private fun island(){hero("Dynamic Island","One adaptive surface for notifications and live activity.");toggle("Enable Dynamic Island",s.island.enabled){s=s.copy(island=s.island.copy(enabled=it));save()};toggle("Adapt to camera cutout",s.island.cutoutAware){s=s.copy(island=s.island.copy(cutoutAware=it));save()};toggle("Blur around cutout",s.island.blurSurroundingCutout){s=s.copy(island=s.island.copy(blurSurroundingCutout=it));save()};slider("Width",72,180,s.island.width," dp"){s=s.copy(island=s.island.copy(width=it));save()};slider("Height",24,70,s.island.height," dp"){s=s.copy(island=s.island.copy(height=it));save()};glassCard("●  Dynamic Island","Calls • media • timers • recording • navigation • notifications")}
    private fun quick(){hero("Quick Space","A tiny edge handle expands into your tools.");toggle("Enable Quick Space",s.quickSpace.enabled){s=s.copy(quickSpace=s.quickSpace.copy(enabled=it));save()};slider("Trigger distance",40,180,s.quickSpace.triggerDistance," px"){s=s.copy(quickSpace=s.quickSpace.copy(triggerDistance=it));save()};choice("Right edge","Swipe inward",QuickEdge.RIGHT,s.quickSpace.edge){s=s.copy(quickSpace=s.quickSpace.copy(edge=it));save()};choice("Left edge","Swipe inward",QuickEdge.LEFT,s.quickSpace.edge){s=s.copy(quickSpace=s.quickSpace.copy(edge=it));save()};glassCard("Quick Space","Notes · Voice · Calculator · Screenshot · Clipboard · Recent")}
    private fun control(){hero("Control Center","Controls rise from the wallpaper as one glass surface.");toggle("Enable Control Center",s.controlCenter.enabled){s=s.copy(controlCenter=s.controlCenter.copy(enabled=it));save()};slider("Tile columns",1,4,s.controlCenter.columns,""){s=s.copy(controlCenter=s.controlCenter.copy(columns=it));save()};slider("Tile radius",10,40,s.controlCenter.tileRadius," dp"){s=s.copy(controlCenter=s.controlCenter.copy(tileRadius=it));save()};glassCard("Control Center","Connectivity • media • brightness • volume • quick actions")}
    private fun windows(){hero("Floating windows","Move, resize and snap supported applications.");toggle("Enable floating windows",s.floatingWindows.enabled){s=s.copy(floatingWindows=s.floatingWindows.copy(enabled=it));save()};toggle("Resize edges",s.floatingWindows.edgeResize){s=s.copy(floatingWindows=s.floatingWindows.copy(edgeResize=it));save()};toggle("Resize corners",s.floatingWindows.cornerResize){s=s.copy(floatingWindows=s.floatingWindows.copy(cornerResize=it));save()};toggle("Snap to edges",s.floatingWindows.snapWindows){s=s.copy(floatingWindows=s.floatingWindows.copy(snapWindows=it));save()};glassCard("Window physics","Aether uses Android-supported windowing paths and keeps unsupported apps full-screen.")}
    private fun split(){hero("Split screen","Two apps. One fluid workspace.");toggle("Enable split screen",s.splitScreen.enabled){s=s.copy(splitScreen=s.splitScreen.copy(enabled=it));save()};slider("Default ratio",30,70,s.splitScreen.defaultRatio,"%"){s=s.copy(splitScreen=s.splitScreen.copy(defaultRatio=it));save()};toggle("Custom divider",s.splitScreen.allowCustomRatio){s=s.copy(splitScreen=s.splitScreen.copy(allowCustomRatio=it));save()};toggle("Remember layouts",s.splitScreen.rememberLayouts){s=s.copy(splitScreen=s.splitScreen.copy(rememberLayouts=it));save()};glassCard("Divider preview","Drag the divider to give either app more room.")}
    private fun security(){hero("Aether Security","Protect apps with your phone's biometrics.");toggle("Enable App Lock",s.security.appLockEnabled){s=s.copy(security=s.security.copy(appLockEnabled=it));save()};toggle("Relock when leaving",s.security.relockOnLeave){s=s.copy(security=s.security.copy(relockOnLeave=it));save()};toggle("Relock on screen off",s.security.relockOnScreenOff){s=s.copy(security=s.security.copy(relockOnScreenOff=it));save()};glassCard("◉  Biometrics","Face or fingerprint through Android BiometricPrompt. No emergency keypad.")}
    private fun ready(){hero("You're ready","Everything can be changed later in Aether Settings.");glassCard("AETHER","Home • Grid • Glass • Dock • Island • Quick Space\nControl Center • Windows • Split Screen • Security")}
    private fun hero(a:String,b:String){content.addView(TextView(context).apply{text=a;textSize=40f;setTextColor(Color.WHITE);gravity=Gravity.CENTER;setPadding(0,dp(28),0,dp(4))},lp(-1,80));content.addView(TextView(context).apply{text=b;textSize=16f;setTextColor(0xDFFFFFFF.toInt());gravity=Gravity.CENTER;setLineSpacing(5f,1f)},lp(-1,70))}
    private fun <T> choice(head:String,body:String,value:T,selected:T,a:(T)->Unit){val box=LinearLayout(context).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(18),dp(15),dp(18),dp(15));setBackground(glassDrawable());setOnClickListener{a(value)}};box.addView(TextView(context).apply{text=(if(value==selected)"●  " else "○  ")+head;textSize=16f;setTextColor(Color.WHITE);typeface=Typeface.DEFAULT_BOLD});box.addView(TextView(context).apply{text=body;textSize=12f;setTextColor(0xBFFFFFFF.toInt());setPadding(dp(24),dp(5),0,0)});content.addView(box,lp(-1,-2).also{it.setMargins(0,dp(5),0,dp(5))})}
    private fun toggle(label:String,v:Boolean,a:(Boolean)->Unit){val r=LinearLayout(context).apply{gravity=Gravity.CENTER_VERTICAL;setPadding(dp(18),0,dp(10),0);setBackground(glassDrawable())};r.addView(TextView(context).apply{text=label;textSize=15f;setTextColor(Color.WHITE)},LinearLayout.LayoutParams(0,dp(58),1f));r.addView(Switch(context).apply{isChecked=v;setOnCheckedChangeListener{_,x->a(x)}},LinearLayout.LayoutParams(dp(60),dp(56)));content.addView(r,lp(-1,60).also{it.setMargins(0,dp(5),0,dp(5))})}
    private fun slider(label:String,min:Int,max:Int,value:Int,suffix:String,a:(Int)->Unit){val box=LinearLayout(context).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(18),dp(12),dp(18),dp(8));setBackground(glassDrawable())};box.addView(TextView(context).apply{text=label;textSize=15f;setTextColor(Color.WHITE)});val out=TextView(context).apply{text="$value$suffix";textSize=14f;setTextColor(Color.WHITE)};box.addView(out);box.addView(SeekBar(context).apply{this.max=max-min;progress=(value-min).coerceIn(0,this.max);setOnSeekBarChangeListener(object:SeekBar.OnSeekBarChangeListener{override fun onProgressChanged(v:SeekBar?,p:Int,u:Boolean){val n=p+min;out.text="$n$suffix";if(u)a(n)};override fun onStartTrackingTouch(v:SeekBar?){ };override fun onStopTrackingTouch(v:SeekBar?){ }})});content.addView(box,lp(-1,82).also{it.setMargins(0,dp(5),0,dp(5))})}
    private fun previewGrid(){content.addView(GridPreview(context,s.grid.columns,s.grid.rows),lp(-1,180).also{it.setMargins(0,dp(12),0,0)})}
    private fun glassCard(head:String,body:String){val box=LinearLayout(context).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(20),dp(18),dp(20),dp(18));setBackground(glassDrawable())};box.addView(TextView(context).apply{text=head;textSize=18f;setTextColor(Color.WHITE);typeface=Typeface.DEFAULT_BOLD});box.addView(TextView(context).apply{text=body;textSize=13f;setTextColor(0xDFFFFFFF.toInt());setPadding(0,dp(8),0,0)});content.addView(box,lp(-1,-2).also{it.setMargins(0,dp(8),0,dp(8))})}
    private fun glassDrawable()=android.graphics.drawable.GradientDrawable().apply{cornerRadius=dp(s.glass.cornerRadius).toFloat();setColor(Color.argb((s.glass.opacity*2.55).roundToInt().coerceIn(80,220),255,255,255));setStroke(dp(1),0x35FFFFFF)}
    private fun save(){store.save(s)};private fun dp(v:Int)= (v*density).roundToInt();private fun lp(w:Int,h:Int)=LinearLayout.LayoutParams(if(w<0)w else dp(w),if(h<0)-2 else dp(h))
}
private class WallpaperBlurView(c:Context):View(c){private val p=Paint(Paint.ANTI_ALIAS_FLAG);private val wallpaper=runCatching{WallpaperManager.getInstance(c).drawable}.getOrNull();init{if(Build.VERSION.SDK_INT>=31)setRenderEffect(RenderEffect.createBlurEffect(24f,24f,Shader.TileMode.CLAMP))};override fun onDraw(c:Canvas){wallpaper?.let{it.setBounds(0,0,width,height);it.draw(c)};p.color=0x9005080D.toInt();c.drawRect(0f,0f,width.toFloat(),height.toFloat(),p)}}
private class GridPreview(c:Context,private val cols:Int,private val rows:Int):View(c){private val p=Paint(Paint.ANTI_ALIAS_FLAG);override fun onDraw(c:Canvas){val gap=8f;val cell=(width-gap*(cols+1))/cols.toFloat();val icon=(cell*.62f).coerceAtLeast(12f);for(r in 0 until rows)for(col in 0 until cols){val x=gap+col*(cell+gap);val y=gap+r*(height-gap*2)/rows;p.color=0x58FFFFFF;c.drawRoundRect(x+(cell-icon)/2,y+8,x+(cell+icon)/2,y+8+icon,icon*.28f,icon*.28f,p)}}}
private class GlassButton(c:Context,textValue:String,click:()->Unit):TextView(c){init{text=textValue;textSize=17f;gravity=Gravity.CENTER;setTextColor(Color.WHITE);typeface=Typeface.DEFAULT_BOLD;setBackground(android.graphics.drawable.GradientDrawable().apply{cornerRadius=100f;setColor(0xB8FFFFFF.toInt());setStroke(1,0x70FFFFFF)});setOnClickListener{click()}}}
