package com.aether.launcher.settings

import android.app.WallpaperManager
import android.content.Context
import android.graphics.*
import android.graphics.drawable.Drawable
import android.os.Build
import android.view.*
import android.widget.*
import kotlin.math.roundToInt

/** Full-screen first-run wizard. Every page has a clear Continue action and a live visual preview. */
class AetherSetupView(context: Context, private val onFinished: () -> Unit) : FrameLayout(context) {
    private val store=AetherSettingsStore(context); private var s=store.load(); private var page=0
    private val pages=listOf("Hello","Home","Grid","Glass","Dock","Dynamic Island","Quick Space","Control Center","Floating Windows","Split Screen","Security","Ready")
    private val content=LinearLayout(context).apply{orientation=LinearLayout.VERTICAL;gravity=Gravity.CENTER_HORIZONTAL}
    private val background=WallpaperBlurView(context)
    private val density=resources.displayMetrics.density
    init { addView(background,LayoutParams(-1,-1)); addView(GlassScroll(context),LayoutParams(-1,-1)); render() }
    private inner class GlassScroll(c:Context):ScrollView(c){ init{isFillViewport=true;setBackgroundColor(Color.TRANSPARENT);addView(content,LayoutParams(-1,-1));setClipToPadding(false);content.setPadding(dp(26),dp(52),dp(26),dp(30))} }
    private fun render(){content.removeAllViews();
        val step=TextView(context).apply{text="AETHER  •  ${page+1}/${pages.size}";textSize=12f;setTextColor(0xAFFFFFFF.toInt());gravity=Gravity.CENTER}
        content.addView(step,lp(-1,30));
        when(page){0->hello();1->home();2->grid();3->glass();4->dock();5->island();6->quick();7->control();8->windows();9->split();10->security();11->ready()}
        content.addView(Space(dp(18)),lp(-1,18));
        val action=GlassButton(context,if(page==pages.lastIndex)"Enter Aether" else "Continue  →"){if(page==pages.lastIndex){store.save(s.copy(setupComplete=true));onFinished()}else{page++;render()}}
        content.addView(action,lp(-1,62));
        if(page>0){val back=TextView(context).apply{text="Back";textSize=14f;setTextColor(0xBFFFFFFF.toInt());gravity=Gravity.CENTER;setOnClickListener{page--;render()}};content.addView(back,lp(-1,48))}
    }
    private fun hello(){title("hello","A new way to use Android."); val t=TextView(context).apply{text="AETHER";textSize=14f;letterSpacing=.28f;setTextColor(0xBFFFFFFF.toInt());gravity=Gravity.CENTER};content.addView(t,lp(-1,60));val line=TextView(context).apply{text="Aether will shape your home, apps and quick actions around the way you use your phone.";textSize=16f;setTextColor(Color.WHITE);gravity=Gravity.CENTER;setLineSpacing(6f,1f)};content.addView(line,lp(-1,-2));}
    private fun home(){title("Your home","Choose how Aether organizes your apps."); choice("All apps on Home","Every installed launcher app appears directly on your pages.",HomeMode.ALL_APPS,s.homeMode){s=s.copy(homeMode=it);save()};choice("Home + App Drawer","Keep a clean home and swipe up for every app.",HomeMode.HOME_AND_DRAWER,s.homeMode){s=s.copy(homeMode=it);save()};choice("App Drawer only","A minimal home with your app drawer as the main space.",HomeMode.DRAWER_ONLY,s.homeMode){s=s.copy(homeMode=it);save()};previewGrid()}
    private fun grid(){title("Your grid","Pick the density. Aether scales icons to fit naturally."); val options=listOf(4 to 4,4 to 5,5 to 5,5 to 6,6 to 6,6 to 7,7 to 7,8 to 8,9 to 9);options.forEach{(c,r)->choice("${c} × ${r}","${c*r} positions",c to r, s.grid.columns to s.grid.rows){s=s.copy(grid=s.grid.copy(columns=it.first,rows=it.second,iconSize=(420/it.first).coerceIn(34,62)));save()}};toggle("App labels",s.grid.showLabels){s=s.copy(grid=s.grid.copy(showLabels=it));save()};previewGrid()}
    private fun glass(){title("Liquid glass","Aether surfaces stay translucent, soft and dimensional.");slider("Opacity",45,100,s.glass.opacity,"%"){v->s=s.copy(glass=s.glass.copy(opacity=v));save()};slider("Blur",4,50,s.glass.blur," px"){v->s=s.copy(glass=s.glass.copy(blur=v));save()};slider("Corner radius",8,42,s.glass.cornerRadius," dp"){v->s=s.copy(glass=s.glass.copy(cornerRadius=v));save()};slider("Refraction",0,40,s.glass.refraction,"%"){v->s=s.copy(glass=s.glass.copy(refraction=v));save()};glassCard("Material preview","Light bends around the surface while the wallpaper remains visible underneath.")}
    private fun dock(){title("Your dock","Keep your most-used apps one gesture away.");toggle("Show dock",s.dock.enabled){s=s.copy(dock=s.dock.copy(enabled=it));save()};slider("Apps",3,8,s.dock.appCount," apps"){v->s=s.copy(dock=s.dock.copy(appCount=v));save()};toggle("Smart groups",s.dock.smartGroups){s=s.copy(dock=s.dock.copy(smartGroups=it));save()};toggle("Group similar companies",s.dock.groupByCompany){s=s.copy(dock=s.dock.copy(groupByCompany=it));save()};toggle("Group by category",s.dock.groupByCategory){s=s.copy(dock=s.dock.copy(groupByCategory=it));save()};glassCard("Smart grouping","Similar apps can collapse into a single living group instead of filling your home.")}
    private fun island(){title("Dynamic Island","One adaptive surface for notifications and live activity.");toggle("Enable Dynamic Island",s.island.enabled){s=s.copy(island=s.island.copy(enabled=it));save()};toggle("Adapt to camera cutout",s.island.cutoutAware){s=s.copy(island=s.island.copy(cutoutAware=it));save()};toggle("Blur around cutout",s.island.blurSurroundingCutout){s=s.copy(island=s.island.copy(blurSurroundingCutout=it));save()};slider("Width",72,180,s.island.width," dp"){v->s=s.copy(island=s.island.copy(width=v));save()};slider("Height",24,70,s.island.height," dp"){v->s=s.copy(island=s.island.copy(height=v));save()};glassCard("●  Dynamic Island","Calls • media • timers • recording • navigation • notifications")}
    private fun quick(){title("Quick Space","A tiny edge handle expands into your tools.");toggle("Enable Quick Space",s.quickSpace.enabled){s=s.copy(quickSpace=s.quickSpace.copy(enabled=it));save()};slider("Trigger distance",40,180,s.quickSpace.triggerDistance," px"){v->s=s.copy(quickSpace=s.quickSpace.copy(triggerDistance=v));save()};choice("Right edge","Swipe inward",QuickEdge.RIGHT,s.quickSpace.edge){s=s.copy(quickSpace=s.quickSpace.copy(edge=it));save()};choice("Left edge","Swipe inward",QuickEdge.LEFT,s.quickSpace.edge){s=s.copy(quickSpace=s.quickSpace.copy(edge=it));save()};glassCard("Quick Space","Notes  ·  Voice  ·  Calculator  ·  Screenshot  ·  Clipboard  ·  Recent")}
    private fun control(){title("Control Center","Your controls, rebuilt as a glass surface.");toggle("Enable Control Center",s.controlCenter.enabled){s=s.copy(controlCenter=s.controlCenter.copy(enabled=it));save()};slider("Tile columns",1,4,s.controlCenter.columns,""){v->s=s.copy(controlCenter=s.controlCenter.copy(columns=v));save()};slider("Tile radius",10,40,s.controlCenter.tileRadius," dp"){v->s=s.copy(controlCenter=s.controlCenter.copy(tileRadius=v));save()};glassCard("Control Center","Wi‑Fi  Bluetooth  Airplane  Rotation  Flashlight  DND\nBrightness and volume become fluid controls.")}
    private fun windows(){title("Floating windows","Open supported apps as movable surfaces.");toggle("Enable floating windows",s.floatingWindows.enabled){s=s.copy(floatingWindows=s.floatingWindows.copy(enabled=it));save()};toggle("Resize edges",s.floatingWindows.edgeResize){s=s.copy(floatingWindows=s.floatingWindows.copy(edgeResize=it));save()};toggle("Resize corners",s.floatingWindows.cornerResize){s=s.copy(floatingWindows=s.floatingWindows.copy(cornerResize=it));save()};toggle("Snap to edges",s.floatingWindows.snapWindows){s=s.copy(floatingWindows=s.floatingWindows.copy(snapWindows=it));save()};glassCard("Move • resize • snap","Aether uses Android's supported windowing paths; unsupported apps stay full-screen.")}
    private fun split(){title("Split screen","Two apps. One fluid workspace.");toggle("Enable split screen",s.splitScreen.enabled){s=s.copy(splitScreen=s.splitScreen.copy(enabled=it));save()};slider("Default ratio",30,70,s.splitScreen.defaultRatio,"%"){v->s=s.copy(splitScreen=s.splitScreen.copy(defaultRatio=v));save()};toggle("Custom divider",s.splitScreen.allowCustomRatio){s=s.copy(splitScreen=s.splitScreen.copy(allowCustomRatio=it));save()};toggle("Remember layouts",s.splitScreen.rememberLayouts){s=s.copy(splitScreen=s.splitScreen.copy(rememberLayouts=it));save()};glassCard("Split preview","Drag the divider to give either app more room.")}
    private fun security(){title("Aether Security","Protect apps with the biometric system on your phone.");toggle("Enable App Lock",s.security.appLockEnabled){s=s.copy(security=s.security.copy(appLockEnabled=it));save()};toggle("Relock when leaving",s.security.relockOnLeave){s=s.copy(security=s.security.copy(relockOnLeave=it));save()};toggle("Relock on screen off",s.security.relockOnScreenOff){s=s.copy(security=s.security.copy(relockOnScreenOff=it));save()};glassCard("◉  Biometrics","Aether uses Android biometric authentication. No emergency keypad is added to the Aether lock screen.")}
    private fun ready(){title("You're ready","Your choices are saved and every one can be changed later.");glassCard("AETHER","Home  •  Grid  •  Glass  •  Dock  •  Island  •  Quick Space\nControl Center  •  Windows  •  Split Screen  •  Security")}
    private fun title(a:String,b:String){content.addView(TextView(context).apply{text=a;textSize=40f;setTextColor(Color.WHITE);typeface=Typeface.create("sans-serif",Typeface.NORMAL);gravity=Gravity.CENTER;setPadding(0,dp(28),0,dp(4))},lp(-1,74));content.addView(TextView(context).apply{text=b;textSize=16f;setTextColor(0xDFFFFFFF.toInt());gravity=Gravity.CENTER;setLineSpacing(5f,1f)},lp(-1,64))}
    private fun glassCard(head:String,body:String){val box=LinearLayout(context).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(20),dp(18),dp(20),dp(18));setBackground(glassDrawable())};box.addView(TextView(context).apply{text=head;textSize=18f;setTextColor(Color.WHITE);typeface=Typeface.DEFAULT_BOLD});box.addView(TextView(context).apply{text=body;textSize=13f;setTextColor(0xDFFFFFFF.toInt());setPadding(0,dp(8),0,0)});content.addView(box,lp(-1,-2).also{it.setMargins(0,dp(8),0,dp(8))})}
    private fun choice(head:String,body:String,value:Any,selected:Any,a:(Any)->Unit){val box=LinearLayout(context).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(18),dp(15),dp(18),dp(15));setBackground(glassDrawable());isClickable=true;setOnClickListener{a(value)}};box.addView(TextView(context).apply{text=(if(value==selected)"●  " else "○  ")+head;textSize=16f;setTextColor(Color.WHITE);typeface=Typeface.DEFAULT_BOLD});box.addView(TextView(context).apply{text=body;textSize=12f;setTextColor(0xBFFFFFFF.toInt());setPadding(dp(24),dp(5),0,0)});content.addView(box,lp(-1,-2).also{it.setMargins(0,dp(5),0,dp(5))})}
    private fun toggle(label:String,v:Boolean,a:(Boolean)->Unit){val r=LinearLayout(context).apply{gravity=Gravity.CENTER_VERTICAL;setPadding(dp(18),0,dp(10),0);setBackground(glassDrawable())};r.addView(TextView(context).apply{text=label;textSize=15f;setTextColor(Color.WHITE)},lp(0,58,1f));r.addView(Switch(context).apply{isChecked=v;setOnCheckedChangeListener{_,x->a(x)}},lp(60,56));content.addView(r,lp(-1,60).also{it.setMargins(0,dp(5),0,dp(5))})}
    private fun slider(label:String,min:Int,max:Int,value:Int,suffix:String,a:(Int)->Unit){val box=LinearLayout(context).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(18),dp(12),dp(18),dp(8));setBackground(glassDrawable())};val out=TextView(context).apply{text="$value$suffix";textSize=14f;setTextColor(Color.WHITE)};box.addView(TextView(context).apply{text=label;textSize=15f;setTextColor(Color.WHITE)});box.addView(out);box.addView(SeekBar(context).apply{this.max=max-min;progress=(value-min).coerceIn(0,this.max);setOnSeekBarChangeListener(object:SeekBar.OnSeekBarChangeListener{override fun onProgressChanged(x:SeekBar?,p:Int,u:Boolean){val n=p+min;out.text="$n$suffix";if(u)a(n)};override fun onStartTrackingTouch(x:SeekBar?){ };override fun onStopTrackingTouch(x:SeekBar?){ }})});content.addView(box,lp(-1,82).also{it.setMargins(0,dp(5),0,dp(5))})}
    private fun previewGrid(){val g=GridPreview(context,s.grid.columns,s.grid.rows);content.addView(g,lp(-1,180).also{it.setMargins(0,dp(12),0,0)})}
    private fun glassDrawable()=android.graphics.drawable.GradientDrawable().apply{shape=android.graphics.drawable.GradientDrawable.RECTANGLE;cornerRadius=dp(s.glass.cornerRadius).toFloat();setColor(Color.argb((s.glass.opacity*2.55).roundToInt().coerceIn(80,235),255,255,255));setStroke(dp(1),0x35FFFFFF)}
    private fun dp(v:Int)= (v*density).roundToInt();private fun lp(w:Int,h:Int)=LinearLayout.LayoutParams(if(w<0)w else dp(w),if(h<0)-2 else dp(h));private fun Space(h:Int)=View(context)
    private fun save(){store.save(s)}
}

private class WallpaperBlurView(c:Context):View(c){private val paint=Paint(Paint.ANTI_ALIAS_FLAG);private var wallpaper:Drawable?=null;init{wallpaper=runCatching{WallpaperManager.getInstance(c).drawable}.getOrNull();if(Build.VERSION.SDK_INT>=31)setRenderEffect(android.graphics.RenderEffect.createBlurEffect(18f,18f,android.graphics.Shader.TileMode.CLAMP))}
 override fun onDraw(c:Canvas){super.onDraw(c);wallpaper?.let{it.setBounds(0,0,width,height);it.draw(c)};paint.color=0x8A080A10.toInt();c.drawRect(0f,0f,width.toFloat(),height.toFloat(),paint)}}
private class GridPreview(c:Context,private val cols:Int,private val rows:Int):View(c){private val p=Paint(Paint.ANTI_ALIAS_FLAG);override fun onDraw(c:Canvas){val gap=8f;val cell=(width-gap*(cols+1))/cols.toFloat();val icon=(cell*.64f).coerceAtLeast(14f);for(r in 0 until rows)for(col in 0 until cols){val x=gap+col*(cell+gap);val y=gap+r*(height-gap*2)/rows;p.color=0x50FFFFFF;c.drawRoundRect(x+(cell-icon)/2,y+8,x+(cell+icon)/2,y+8+icon,icon*.28f,icon*.28f,p)}}}
private class GlassButton(c:Context,textValue:String,click:()->Unit):TextView(c){init{text=textValue;textSize=17f;gravity=Gravity.CENTER;setTextColor(Color.WHITE);setTypeface(Typeface.DEFAULT,Typeface.BOLD);setBackground(android.graphics.drawable.GradientDrawable().apply{cornerRadius=100f;setColor(0xB8FFFFFF.toInt());setStroke(1,0x70FFFFFF)});setOnClickListener{click()}}}
