package com.aether.launcher.settings

import android.app.AlertDialog
import android.content.Context
import android.content.Intent
import android.graphics.Color
import android.net.Uri
import android.provider.Settings
import android.view.Gravity
import android.view.View
import android.widget.*
import com.aether.launcher.AetherRuntime
import kotlin.math.roundToInt

class AetherSettingsView(context: Context) : ScrollView(context) {
    private val store = AetherSettingsStore(context)
    private var s = store.load()
    private val root = LinearLayout(context).apply { orientation = LinearLayout.VERTICAL; setPadding(dp(20), dp(28), dp(20), dp(36)); setBackgroundColor(0xFF080A0E.toInt()) }
    private var section: String? = null

    init { setFillViewport(true); addView(root); render() }

    private fun render() { root.removeAllViews(); if (section == null) home() else detail(section!!) }

    private fun home() {
        header("Aether Settings", "Every major launcher surface is editable and persisted.")
        panel("${s.homeMode.name.replace('_',' ')}  •  ${s.grid.columns}×${s.grid.rows}\nGlass ${s.glass.opacity}%  •  Dock ${s.dock.appCount}  •  Island ${on(s.island.enabled)}\nQuick Space ${on(s.quickSpace.enabled)}  •  App Lock ${on(s.security.appLockEnabled)}")
        group("Personalize")
        card("Home", "Launcher mode and home behavior", "home")
        card("Grid & Icons", "Columns, rows, spacing, labels and folders", "grid")
        card("Dock", "Favorites count, shape and smart grouping", "dock")
        card("Glass & Appearance", "Blur, opacity, theme and lighting", "appearance")
        card("Motion", "Spring personality and gesture sensitivity", "motion")
        group("Features")
        card("Dynamic Island", "Cutout-aware activities and notifications", "island")
        card("Quick Space", "Edge handle and real tools", "quick")
        card("Control Center", "Tiles, panel and system controls", "control")
        card("Floating Windows", "Window behavior and limits", "windows")
        card("Split Screen", "Ratios and remembered layouts", "split")
        card("Security", "App lock and protected applications", "security")
        group("System")
        card("Permissions & Access", "Open Android permission and access pages", "permissions")
        card("Reset", "Restore Aether feature preferences", "reset")
    }

    private fun detail(k: String) {
        header(labelFor(k), descriptionFor(k))
        when (k) {
            "home" -> { choice("Home mode", HomeMode.values().toList(), s.homeMode) { s = s.copy(homeMode = it); save() } }
            "grid" -> { int("Columns",3,7,s.grid.columns){g->s=s.copy(grid=s.grid.copy(columns=g));save()}; int("Rows",4,9,s.grid.rows){g->s=s.copy(grid=s.grid.copy(rows=g));save()}; int("Icon size",40,72,s.grid.iconSize){g->s=s.copy(grid=s.grid.copy(iconSize=g));save()}; int("Horizontal spacing",4,28,s.grid.horizontalSpacing){g->s=s.copy(grid=s.grid.copy(horizontalSpacing=g));save()}; int("Vertical spacing",6,32,s.grid.verticalSpacing){g->s=s.copy(grid=s.grid.copy(verticalSpacing=g));save()}; int("Horizontal padding",8,40,s.grid.horizontalPadding){g->s=s.copy(grid=s.grid.copy(horizontalPadding=g));save()}; toggle("Show labels",s.grid.showLabels){s=s.copy(grid=s.grid.copy(showLabels=it));save()}; int("Label size",9,16,s.grid.labelSize){g->s=s.copy(grid=s.grid.copy(labelSize=g));save()}; choice("Folder style",FolderStyle.values().toList(),s.grid.folderStyle){s=s.copy(grid=s.grid.copy(folderStyle=it));save()}; int("Folder radius",8,40,s.grid.folderRadius){g->s=s.copy(grid=s.grid.copy(folderRadius=g));save()} }
            "dock" -> { toggle("Dock enabled",s.dock.enabled){s=s.copy(dock=s.dock.copy(enabled=it));save()}; int("Dock favorites",3,8,s.dock.appCount){v->s=s.copy(dock=s.dock.copy(appCount=v));save()}; int("Dock height",56,110,s.dock.height){v->s=s.copy(dock=s.dock.copy(height=v));save()}; int("Dock radius",12,44,s.dock.radius){v->s=s.copy(dock=s.dock.copy(radius=v));save()}; toggle("Smart grouping",s.dock.smartGroups){s=s.copy(dock=s.dock.copy(smartGroups=it));save()}; toggle("Group by company",s.dock.groupByCompany){s=s.copy(dock=s.dock.copy(groupByCompany=it));save()}; toggle("Group by category",s.dock.groupByCategory){s=s.copy(dock=s.dock.copy(groupByCategory=it));save()} }
            "appearance" -> { choice("Theme",AppearanceTheme.values().toList(),s.appearance.theme){s=s.copy(appearance=s.appearance.copy(theme=it));save()}; int("Glass opacity",45,100,s.glass.opacity){v->s=s.copy(glass=s.glass.copy(opacity=v));save()}; int("Blur",0,50,s.glass.blur){v->s=s.copy(glass=s.glass.copy(blur=v));save()}; int("Saturation",80,135,s.glass.saturation){v->s=s.copy(glass=s.glass.copy(saturation=v));save()}; int("Highlights",0,100,s.glass.highlight){v->s=s.copy(glass=s.glass.copy(highlight=v));save()}; int("Depth",0,20,s.glass.depth){v->s=s.copy(glass=s.glass.copy(depth=v));save()}; int("Corner radius",8,42,s.glass.cornerRadius){v->s=s.copy(glass=s.glass.copy(cornerRadius=v));save()}; int("Wallpaper dim",0,40,s.appearance.wallpaperDim){v->s=s.copy(appearance=s.appearance.copy(wallpaperDim=v));save()}; toggle("Show time",s.appearance.showTime){s=s.copy(appearance=s.appearance.copy(showTime=it));save()}; toggle("Show AETHER label",s.appearance.showAetherLabel){s=s.copy(appearance=s.appearance.copy(showAetherLabel=it));save()} }
            "motion" -> { choice("Preset",MotionPreset.values().toList(),s.motion.preset){s=s.copy(motion=s.motion.copy(preset=it));save()}; int("Speed",50,160,s.motion.speed){v->s=s.copy(motion=s.motion.copy(speed=v));save()}; int("Spring strength",150,800,s.motion.springStrength){v->s=s.copy(motion=s.motion.copy(springStrength=v));save()}; int("Damping",10,80,s.motion.damping){v->s=s.copy(motion=s.motion.copy(damping=v));save()}; int("Bounce",0,40,s.motion.bounce){v->s=s.copy(motion=s.motion.copy(bounce=v));save()}; int("Gesture sensitivity",10,100,s.motion.gestureSensitivity){v->s=s.copy(motion=s.motion.copy(gestureSensitivity=v));save()} }
            "island" -> { toggle("Enabled",s.island.enabled){s=s.copy(island=s.island.copy(enabled=it));save()}; toggle("Cutout aware",s.island.cutoutAware){s=s.copy(island=s.island.copy(cutoutAware=it));save()}; int("Width",72,180,s.island.width){v->s=s.copy(island=s.island.copy(width=v));save()}; int("Height",24,70,s.island.height){v->s=s.copy(island=s.island.copy(height=v));save()}; int("Corner radius",8,35,s.island.radius){v->s=s.copy(island=s.island.copy(radius=v));save()}; toggle("Notifications",s.island.showNotifications){s=s.copy(island=s.island.copy(showNotifications=it));save()}; toggle("Media",s.island.showMedia){s=s.copy(island=s.island.copy(showMedia=it));save()}; toggle("Calls",s.island.showCalls){s=s.copy(island=s.island.copy(showCalls=it));save()}; toggle("Timers",s.island.showTimers){s=s.copy(island=s.island.copy(showTimers=it));save()}; toggle("Recording",s.island.showRecording){s=s.copy(island=s.island.copy(showRecording=it));save()}; toggle("Navigation",s.island.showNavigation){s=s.copy(island=s.island.copy(showNavigation=it));save()} }
            "quick" -> { toggle("Enabled",s.quickSpace.enabled){s=s.copy(quickSpace=s.quickSpace.copy(enabled=it));save()}; choice("Edge",QuickEdge.values().toList(),s.quickSpace.edge){s=s.copy(quickSpace=s.quickSpace.copy(edge=it));save()}; int("Handle thickness",3,12,s.quickSpace.handleThickness){v->s=s.copy(quickSpace=s.quickSpace.copy(handleThickness=v));save()}; int("Handle length",24,90,s.quickSpace.handleLength){v->s=s.copy(quickSpace=s.quickSpace.copy(handleLength=v));save()}; int("Trigger distance",40,180,s.quickSpace.triggerDistance){v->s=s.copy(quickSpace=s.quickSpace.copy(triggerDistance=v));save()}; toggle("Notes",s.quickSpace.notes){s=s.copy(quickSpace=s.quickSpace.copy(notes=it));save()}; toggle("Voice recorder",s.quickSpace.recorder){s=s.copy(quickSpace=s.quickSpace.copy(recorder=it));save()}; toggle("Calculator",s.quickSpace.calculator){s=s.copy(quickSpace=s.quickSpace.copy(calculator=it));save()}; toggle("Screenshot",s.quickSpace.screenshot){s=s.copy(quickSpace=s.quickSpace.copy(screenshot=it));save()}; toggle("Clipboard",s.quickSpace.clipboard){s=s.copy(quickSpace=s.quickSpace.copy(clipboard=it));save()} }
            "control" -> { toggle("Enabled",s.controlCenter.enabled){s=s.copy(controlCenter=s.controlCenter.copy(enabled=it));save()}; choice("Gesture corner",ControlEdge.values().toList(),s.controlCenter.edge){s=s.copy(controlCenter=s.controlCenter.copy(edge=it));save()}; int("Tile columns",1,4,s.controlCenter.columns){v->s=s.copy(controlCenter=s.controlCenter.copy(columns=v));save()}; int("Tile radius",10,40,s.controlCenter.tileRadius){v->s=s.copy(controlCenter=s.controlCenter.copy(tileRadius=v));save()}; toggle("Brightness",s.controlCenter.showBrightness){s=s.copy(controlCenter=s.controlCenter.copy(showBrightness=it));save()}; toggle("Volume",s.controlCenter.showVolume){s=s.copy(controlCenter=s.controlCenter.copy(showVolume=it));save()}; toggle("Wi-Fi",s.controlCenter.showWifi){s=s.copy(controlCenter=s.controlCenter.copy(showWifi=it));save()}; toggle("Bluetooth",s.controlCenter.showBluetooth){s=s.copy(controlCenter=s.controlCenter.copy(showBluetooth=it));save()}; toggle("Airplane",s.controlCenter.showAirplane){s=s.copy(controlCenter=s.controlCenter.copy(showAirplane=it));save()}; toggle("Rotation",s.controlCenter.showRotation){s=s.copy(controlCenter=s.controlCenter.copy(showRotation=it));save()}; toggle("Flashlight",s.controlCenter.showFlashlight){s=s.copy(controlCenter=s.controlCenter.copy(showFlashlight=it));save()}; toggle("DND",s.controlCenter.showDnd){s=s.copy(controlCenter=s.controlCenter.copy(showDnd=it));save()} }
            "windows" -> { toggle("Enabled",s.floatingWindows.enabled){s=s.copy(floatingWindows=s.floatingWindows.copy(enabled=it));save()}; int("Default width",50,95,s.floatingWindows.defaultWidth){v->s=s.copy(floatingWindows=s.floatingWindows.copy(defaultWidth=v));save()}; int("Default height",40,90,s.floatingWindows.defaultHeight){v->s=s.copy(floatingWindows=s.floatingWindows.copy(defaultHeight=v));save()}; int("Window radius",10,42,s.floatingWindows.radius){v->s=s.copy(floatingWindows=s.floatingWindows.copy(radius=v));save()}; int("Opacity",55,100,s.floatingWindows.transparency){v->s=s.copy(floatingWindows=s.floatingWindows.copy(transparency=v));save()}; int("Maximum windows",1,6,s.floatingWindows.maxWindows){v->s=s.copy(floatingWindows=s.floatingWindows.copy(maxWindows=v));save()}; toggle("Resize edges",s.floatingWindows.edgeResize){s=s.copy(floatingWindows=s.floatingWindows.copy(edgeResize=it));save()}; toggle("Resize corners",s.floatingWindows.cornerResize){s=s.copy(floatingWindows=s.floatingWindows.copy(cornerResize=it));save()}; toggle("Snap windows",s.floatingWindows.snapWindows){s=s.copy(floatingWindows=s.floatingWindows.copy(snapWindows=it));save()}; toggle("Remember positions",s.floatingWindows.rememberPositions){s=s.copy(floatingWindows=s.floatingWindows.copy(rememberPositions=it));save()} }
            "split" -> { toggle("Enabled",s.splitScreen.enabled){s=s.copy(splitScreen=s.splitScreen.copy(enabled=it));save()}; int("Default ratio",30,70,s.splitScreen.defaultRatio){v->s=s.copy(splitScreen=s.splitScreen.copy(defaultRatio=v));save()}; toggle("Custom ratio",s.splitScreen.allowCustomRatio){s=s.copy(splitScreen=s.splitScreen.copy(allowCustomRatio=it));save()}; toggle("Remember layouts",s.splitScreen.rememberLayouts){s=s.copy(splitScreen=s.splitScreen.copy(rememberLayouts=it));save()}; toggle("Snap divider",s.splitScreen.snapToEdges){s=s.copy(splitScreen=s.splitScreen.copy(snapToEdges=it));save()}; int("Divider thickness",2,12,s.splitScreen.dividerThickness){v->s=s.copy(splitScreen=s.splitScreen.copy(dividerThickness=v));save()} }
            "security" -> { toggle("App Lock",s.security.appLockEnabled){s=s.copy(security=s.security.copy(appLockEnabled=it));save()}; toggle("Relock when leaving",s.security.relockOnLeave){s=s.copy(security=s.security.copy(relockOnLeave=it));save()}; toggle("Relock on screen off",s.security.relockOnScreenOff){s=s.copy(security=s.security.copy(relockOnScreenOff=it));save()}; int("Relock timeout",0,300,s.security.relockTimeoutSeconds){v->s=s.copy(security=s.security.copy(relockTimeoutSeconds=v));save()}; toggle("Use biometrics",s.security.useBiometrics){s=s.copy(security=s.security.copy(useBiometrics=it));save()}; toggle("Use device credential",s.security.useDeviceCredential){s=s.copy(security=s.security.copy(useDeviceCredential=it));save()}; toggle("Hide locked apps",s.security.hideLockedApps){s=s.copy(security=s.security.copy(hideLockedApps=it));save()}; text("Protected apps",19f,Color.WHITE,true); AetherRuntime.registry.launcher.apps().sortedBy{it.label.lowercase()}.forEach { app -> row(app.label, AetherRuntime.security.protectedApps().contains(app.packageName)) { checked -> if (checked) AetherRuntime.security.protect(app.packageName) else AetherRuntime.security.unprotect(app.packageName) } } }
            "permissions" -> { action("Default launcher","Choose Aether as the Home app"){context.startActivity(Intent(Settings.ACTION_HOME_SETTINGS))}; action("Overlay permission","Allow Edge Space and Dynamic Island"){context.startActivity(Intent(Settings.ACTION_MANAGE_OVERLAY_PERMISSION,Uri.parse("package:${context.packageName}")))}; action("Notification access","Feed real notifications into Aether"){context.startActivity(Intent("android.settings.ACTION_NOTIFICATION_LISTENER_SETTINGS"))}; action("Accessibility","Enable foreground sensing and app lock"){context.startActivity(Intent(Settings.ACTION_ACCESSIBILITY_SETTINGS))}; action("Write system settings","Brightness, rotation and DND controls"){context.startActivity(Intent(Settings.ACTION_MANAGE_WRITE_SETTINGS,Uri.parse("package:${context.packageName}")))} }
            "reset" -> { panel("This resets Aether preferences to defaults. Your saved notes, history and protected-app list are kept."); action("Reset Aether","Start the setup wizard again"){store.resetSetup();Toast.makeText(context,"Aether reset. Reopen the launcher to run setup again.",Toast.LENGTH_LONG).show()} }
        }
    }

    private fun header(t:String, sub:String){ val row=LinearLayout(context).apply{gravity=Gravity.CENTER_VERTICAL}; if(section!=null) row.addView(Button(context).apply{text="‹";setOnClickListener{section=null;render()}},LinearLayout.LayoutParams(dp(54),dp(54))); val wrap=LinearLayout(context).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(8),0,0,0)};wrap.addView(TextView(context).apply{text=t;textSize=30f;setTextColor(Color.WHITE);typeface=android.graphics.Typeface.DEFAULT_BOLD});wrap.addView(TextView(context).apply{text=sub;textSize=13f;setTextColor(0xBFFFFFFF.toInt())});row.addView(wrap,LinearLayout.LayoutParams(0,-2,1f));root.addView(row,LinearLayout.LayoutParams(-1,dp(82)))}
    private fun group(t:String){root.addView(TextView(context).apply{text=t;textSize=18f;setTextColor(Color.WHITE);typeface=android.graphics.Typeface.DEFAULT_BOLD},LinearLayout.LayoutParams(-1,dp(42)))}
    private fun card(t:String,b:String,k:String){root.addView(Button(context).apply{text="$t\n$b";gravity=Gravity.START or Gravity.CENTER_VERTICAL;setTextColor(Color.WHITE);textSize=14f;setPadding(dp(18),0,dp(18),0);setOnClickListener{section=k;render()}},LinearLayout.LayoutParams(-1,dp(70)).apply{bottomMargin=dp(8)})}
    private fun panel(value:String){root.addView(TextView(context).apply{text=value;textSize=13f;setTextColor(Color.WHITE);setPadding(dp(16),dp(16),dp(16),dp(16));setBackgroundColor(0x181F2933)},LinearLayout.LayoutParams(-1,dp(88)).apply{bottomMargin=dp(14)})}
    private fun toggle(label:String,value:Boolean,change:(Boolean)->Unit){val row=LinearLayout(context).apply{gravity=Gravity.CENTER_VERTICAL;setPadding(0,dp(2),0,dp(2))};row.addView(TextView(context).apply{text=label;textSize=14f;setTextColor(Color.WHITE)},LinearLayout.LayoutParams(0,dp(54),1f));row.addView(Switch(context).apply{isChecked=value;setOnCheckedChangeListener{_,v->change(v)}},LinearLayout.LayoutParams(dp(64),dp(52)));root.addView(row)}
    private fun int(label:String,min:Int,max:Int,value:Int,change:(Int)->Unit){val box=LinearLayout(context).apply{orientation=LinearLayout.VERTICAL;setPadding(0,dp(6),0,dp(6))};val head=LinearLayout(context).apply{gravity=Gravity.CENTER_VERTICAL};val name=TextView(context).apply{text=label;textSize=14f;setTextColor(Color.WHITE)};val out=TextView(context).apply{text=value.toString();textSize=12f;setTextColor(0xBFFFFFFF.toInt());gravity=Gravity.END};head.addView(name,LinearLayout.LayoutParams(0,dp(28),1f));head.addView(out,LinearLayout.LayoutParams(dp(54),dp(28)));val bar=SeekBar(context).apply{max=max-min;progress=(value-min).coerceIn(0,max-min);setOnSeekBarChangeListener(object:SeekBar.OnSeekBarChangeListener{override fun onProgressChanged(sb:SeekBar?,p:Int,fromUser:Boolean){val v=p+min;out.text=v.toString();if(fromUser)change(v)};override fun onStartTrackingTouch(sb:SeekBar?){ };override fun onStopTrackingTouch(sb:SeekBar?){ }})};box.addView(head);box.addView(bar);root.addView(box)}
    private fun <E:Enum<E>> choice(label:String,values:List<E>,selected:E,change:(E)->Unit){val row=LinearLayout(context).apply{gravity=Gravity.CENTER_VERTICAL};row.addView(TextView(context).apply{text=label;textSize=14f;setTextColor(Color.WHITE)},LinearLayout.LayoutParams(0,dp(56),1f));val sp=Spinner(context);sp.adapter=ArrayAdapter(context,android.R.layout.simple_spinner_dropdown_item,values.map{it.name.replace('_',' ').lowercase().replaceFirstChar{c->c.uppercase()}});sp.setSelection(values.indexOf(selected));sp.onItemSelectedListener=object:AdapterView.OnItemSelectedListener{override fun onItemSelected(parent:AdapterView<*>?,view:View?,position:Int,id:Long){change(values[position])};override fun onNothingSelected(parent:AdapterView<*>?){}};row.addView(sp,LinearLayout.LayoutParams(dp(190),dp(56)));root.addView(row)}
    private fun row(label:String,checked:Boolean,change:(Boolean)->Unit){val line=LinearLayout(context).apply{gravity=Gravity.CENTER_VERTICAL};line.addView(TextView(context).apply{text=label;textSize=13f;setTextColor(Color.WHITE)},LinearLayout.LayoutParams(0,dp(50),1f));line.addView(CheckBox(context).apply{isChecked=checked;setOnCheckedChangeListener{_,v->change(v)}},LinearLayout.LayoutParams(dp(60),dp(50)));root.addView(line)}
    private fun action(title:String,body:String,click:()->Unit){root.addView(Button(context).apply{text="$title\n$body";gravity=Gravity.START or Gravity.CENTER_VERTICAL;setTextColor(Color.WHITE);textSize=14f;setPadding(dp(18),0,dp(18),0);setOnClickListener{runCatching{click()}.onFailure{Toast.makeText(context,"Unavailable on this device",Toast.LENGTH_SHORT).show()}}},LinearLayout.LayoutParams(-1,dp(72)).apply{bottomMargin=dp(8)})}
    private fun save(){store.save(s); invalidate()}
    private fun on(v:Boolean)=if(v)"ON" else "OFF"
    private fun labelFor(k:String)=mapOf("home" to "Home Settings","grid" to "Grid & Icons","dock" to "Dock Settings","appearance" to "Glass & Appearance","motion" to "Motion Settings","island" to "Island Settings","quick" to "Quick Space Settings","control" to "Control Center Settings","windows" to "Floating Window Settings","split" to "Split Screen Settings","security" to "Security Settings","permissions" to "Permissions & Access","reset" to "Reset Aether")[k] ?: "Aether Settings"
    private fun descriptionFor(k:String)=mapOf("home" to "Choose the launcher layout.","grid" to "Tune density and app presentation.","dock" to "Manage the apps you keep close.","appearance" to "Control Aether's visual material.","motion" to "Tune springs and gestures.","island" to "Control live activity behavior.","quick" to "Tune the edge action surface.","control" to "Tune real system-backed controls.","windows" to "Configure multi-window behavior.","split" to "Configure split-screen defaults.","security" to "Protect selected applications.","permissions" to "Android permissions remain user-controlled.","reset" to "Return feature settings to their defaults.")[k] ?: ""
    private fun dp(v:Int)= (v*resources.displayMetrics.density).roundToInt()
}
