package com.aether.launcher

import android.content.Context
import android.content.Intent
import android.graphics.Canvas
import android.graphics.Color
import android.graphics.Paint
import android.graphics.RectF
import android.graphics.Typeface
import android.graphics.drawable.Drawable
import android.view.MotionEvent
import android.view.View
import androidx.dynamicanimation.animation.DynamicAnimation
import androidx.dynamicanimation.animation.SpringAnimation
import androidx.dynamicanimation.animation.SpringForce
import com.aether.launcher.settings.AetherSettingsStore
import com.aether.launcher.settings.HomeMode
import com.aether.launcher.settings.QuickEdge
import com.aether.launcher.ui.AetherSurface
import com.aether.launcher.ui.AetherSurfaceActivity
import com.aether.launcher.ui.AetherToolsActivity
import kotlin.math.abs
import kotlin.math.min

class AetherHomeView(context:Context):View(context){
 private val p=Paint(Paint.ANTI_ALIAS_FLAG);private val store=AetherSettingsStore(context);private val history=AetherHistoryStore(context);private val dock=AetherDockStore(context);private var cfg=store.load();private val apps get()=AetherRuntime.registry.launcher.apps();private var downX=0f;private var downY=0f;private val d get()=resources.displayMetrics.density;private val quickSpring=SpringAnimation(this,DynamicAnimation.TRANSLATION_X)
 init{setLayerType(View.LAYER_TYPE_SOFTWARE,null);quickSpring.spring=SpringForce(0f).apply{stiffness=560f;dampingRatio=.8f};scaleX=.985f;scaleY=.985f;SpringAnimation(this,DynamicAnimation.SCALE_X).apply{spring=SpringForce(1f).apply{stiffness=520f;dampingRatio=.82f}}.start();SpringAnimation(this,DynamicAnimation.SCALE_Y).apply{spring=SpringForce(1f).apply{stiffness=520f;dampingRatio=.82f}}.start()}
 override fun onDraw(c:Canvas){cfg=store.load();val w=width.toFloat();val h=height.toFloat();p.color=0x42080A0E.toInt();c.drawRect(0f,0f,w,h,p);if(cfg.appearance.showTime){p.color=Color.WHITE;p.textAlign=Paint.Align.CENTER;p.textSize=16f*d;p.typeface=Typeface.DEFAULT_BOLD;c.drawText(timeText(),w/2,h*.10f,p)};if(cfg.appearance.showAetherLabel){p.color=0xB8FFFFFF.toInt();p.textSize=10f*d;p.typeface=Typeface.DEFAULT;c.drawText("AETHER",w/2,h*.10f+20*d,p)};val active=AetherRuntime.registry.island.activity;if(cfg.island.enabled){val iw=min(w*.44f,cfg.island.width*d);val ih=cfg.island.height*d;val y=cfg.island.topOffset*d;p.color=0xE7181B21.toInt();c.drawRoundRect(RectF(w/2-iw/2,y,w/2+iw/2,y+ih),cfg.island.radius*d,cfg.island.radius*d,p);p.color=0x3AFFFFFF;c.drawRoundRect(RectF(w/2-iw/2+1,y+1,w/2+iw/2-1,y+ih-1),cfg.island.radius*d,cfg.island.radius*d,p);if(active.title.isNotBlank()){p.color=Color.WHITE;p.textSize=9f*d;c.drawText(active.title.take(24),w/2,y+ih*.63f,p)}};val cols=cfg.grid.columns.coerceIn(3,7);val gap=cfg.grid.horizontalSpacing*d;val left=cfg.grid.horizontalPadding*d;val icon=cfg.grid.iconSize*d;val cell=(w-left*2-gap*(cols-1))/cols;val top=h*.20f+cfg.grid.verticalPadding*d;val rowH=icon+cfg.grid.verticalSpacing*d+24*d;val shown=when(cfg.homeMode){HomeMode.ALL_APPS->apps.take(cols*cfg.grid.rows);HomeMode.HOME_AND_DRAWER->apps.take(cols*min(cfg.grid.rows,3));HomeMode.DRAWER_ONLY->apps.take(cols*min(cfg.grid.rows,2))};shown.forEachIndexed{i,a->{val col=i%cols;val row=i/cols;val x=left+col*(cell+gap);val y=top+row*rowH;drawGlass(c,RectF(x,y,x+cell,y+icon+4*d),cfg.glass.cornerRadius*d);val ir=RectF(x+cell/2-icon/2,y+2*d,x+cell/2+icon/2,y+2*d+icon);drawIcon(c,AetherRuntime.registry.launcher.icon(a.packageName),ir);if(cfg.grid.showLabels){p.color=0xE6FFFFFF.toInt();p.textAlign=Paint.Align.CENTER;p.textSize=cfg.grid.labelSize*d;c.drawText(a.label.take(13),x+cell/2,y+icon+20*d,p)}}};if(cfg.dock.enabled){val dockH=cfg.dock.height*d;val bottom=h-cfg.dock.bottomPadding*d-dockH;drawGlass(c,RectF(w*.05f,bottom,w*.95f,bottom+dockH),cfg.dock.radius*d);val favorites=dock.favorites().mapNotNull{pkg->apps.firstOrNull{it.packageName==pkg}}.distinctBy{it.packageName};val chosen=(favorites+apps.filterNot{a->favorites.any{it.packageName==a.packageName}}).take(cfg.dock.appCount.coerceAtMost(apps.size));if(chosen.isNotEmpty()){val step=w*.88f/chosen.size;chosen.forEachIndexed{i,a->{val size=min(dockH*.58f,48*d);val cx=w*.06f+step*(i+.5f);drawIcon(c,AetherRuntime.registry.launcher.icon(a.packageName),RectF(cx-size/2,bottom+dockH*.21f,cx+size/2,bottom+dockH*.21f+size))}}}};if(cfg.quickSpace.enabled){val right=cfg.quickSpace.edge==QuickEdge.RIGHT;val th=cfg.quickSpace.handleThickness*d;val len=cfg.quickSpace.handleLength*d;val x=if(right)w-7*d else 2*d;p.color=0xF0FFFFFF.toInt();val r=if(right)RectF(x-th,h*.5f-len/2,x,h*.5f+len/2)else RectF(x,h*.5f-len/2,x+th,h*.5f+len/2);c.drawRoundRect(r,th,th,p)}}
 private fun drawGlass(c:Canvas,r:RectF,radius:Float){p.color=0xA81B2027.toInt();p.setShadowLayer(cfg.glass.depth*d,0f,3*d,0x80000000.toInt());c.drawRoundRect(r,radius,radius,p);p.clearShadowLayer();p.color=0x32FFFFFF;c.drawRoundRect(RectF(r.left+1,r.top+1,r.right-1,r.bottom-1),radius,radius,p);p.color=0x18FFFFFF;c.drawRoundRect(RectF(r.left+2,r.top+2,r.right-2,r.top+maxOf(4f,r.height()*.18f)),radius,radius,p)}
 private fun drawIcon(c:Canvas,icon:Drawable?,r:RectF){icon?:return;icon.setBounds(r.left.toInt(),r.top.toInt(),r.right.toInt(),r.bottom.toInt());icon.draw(c)}
 override fun onTouchEvent(e:MotionEvent):Boolean{when(e.actionMasked){MotionEvent.ACTION_DOWN->{downX=e.x;downY=e.y;return true};MotionEvent.ACTION_UP->{val dx=e.x-downX;val dy=e.y-downY;if(cfg.quickSpace.enabled&&abs(dx)>cfg.quickSpace.triggerDistance&&((cfg.quickSpace.edge==QuickEdge.RIGHT&&downX>width-100*d)||(cfg.quickSpace.edge==QuickEdge.LEFT&&downX<100*d))){quickSpring.animateToFinalPosition(if(cfg.quickSpace.edge==QuickEdge.RIGHT)-20*d else 20*d);start(AetherSurface.QUICK);return true};if(downY<125*d&&abs(dy)>70*d){start(if(dy>0)AetherSurface.NOTIFICATIONS else AetherSurface.CONTROL);return true};if(abs(dy)>90*d&&dy<0&&downY>height*.18f){start(AetherSurface.DRAWER);return true};if(abs(dy)>90*d&&dy>0&&downY<height*.45f){start(AetherSurface.WIDGETS);return true};if(downY>height*.78f&&abs(dx)<30*d&&abs(dy)<30*d){start(AetherSurface.MULTITASK);return true};if(abs(dx)<30*d&&abs(dy)<30*d){launchApp(e.x,e.y);return true}}};return true}
 private fun launchApp(x:Float,y:Float){val cols=cfg.grid.columns.coerceIn(3,7);val gap=cfg.grid.horizontalSpacing*d;val left=cfg.grid.horizontalPadding*d;val icon=cfg.grid.iconSize*d;val cell=(width-left*2-gap*(cols-1))/cols;val top=height*.20f+cfg.grid.verticalPadding*d;val rowH=icon+cfg.grid.verticalSpacing*d+24*d;val col=((x-left)/(cell+gap)).toInt();val row=((y-top)/rowH).toInt();val index=row*cols+col;val shown=when(cfg.homeMode){HomeMode.ALL_APPS->apps.take(cols*cfg.grid.rows);HomeMode.HOME_AND_DRAWER->apps.take(cols*min(cfg.grid.rows,3));HomeMode.DRAWER_ONLY->apps.take(cols*min(cfg.grid.rows,2))};if(col in 0 until cols&&row>=0&&index in shown.indices){history.record(shown[index].packageName);AetherRuntime.registry.launcher.launchIntent(shown[index].packageName)?.let{context.startActivity(it)}}}
 private fun start(s:String){context.startActivity(Intent(context,AetherSurfaceActivity::class.java).putExtra("surface",s))};private fun timeText()=java.text.SimpleDateFormat("HH:mm",java.util.Locale.getDefault()).format(java.util.Date())
}
